//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3615
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.42.
// 
namespace  L3.Cargo.Workstation.Plugins.RadiationDetectorData
{
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Measurements {
        
        private MeasurementsSample[] sampleField;
        
        private uint occupancyIDField;
        
        private decimal schemaVersionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Sample")]
        public MeasurementsSample[] Sample {
            get {
                return this.sampleField;
            }
            set {
                this.sampleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint OccupancyID {
            get {
                return this.occupancyIDField;
            }
            set {
                this.occupancyIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal SchemaVersion {
            get {
                return this.schemaVersionField;
            }
            set {
                this.schemaVersionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class MeasurementsSample {
        
        private MeasurementsSampleMissed_Measurement missed_MeasurementField;
        
        private MeasurementsSampleN_RSP1 n_RSP1Field;
        
        private MeasurementsSampleG_RSP1 g_RSP1Field;
        
        private MeasurementsSampleN_RSP2 n_RSP2Field;
        
        private MeasurementsSampleG_RSP2 g_RSP2Field;
        
        private string timeField;
        
        /// <remarks/>
        public MeasurementsSampleMissed_Measurement Missed_Measurement {
            get {
                return this.missed_MeasurementField;
            }
            set {
                this.missed_MeasurementField = value;
            }
        }
        
        /// <remarks/>
        public MeasurementsSampleN_RSP1 N_RSP1 {
            get {
                return this.n_RSP1Field;
            }
            set {
                this.n_RSP1Field = value;
            }
        }
        
        /// <remarks/>
        public MeasurementsSampleG_RSP1 G_RSP1 {
            get {
                return this.g_RSP1Field;
            }
            set {
                this.g_RSP1Field = value;
            }
        }
        
        /// <remarks/>
        public MeasurementsSampleN_RSP2 N_RSP2 {
            get {
                return this.n_RSP2Field;
            }
            set {
                this.n_RSP2Field = value;
            }
        }
        
        /// <remarks/>
        public MeasurementsSampleG_RSP2 G_RSP2 {
            get {
                return this.g_RSP2Field;
            }
            set {
                this.g_RSP2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Time {
            get {
                return this.timeField;
            }
            set {
                this.timeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class MeasurementsSampleMissed_Measurement {
        
        private string previous_SampleTimeField;
        
        private string current_SampleTimeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Previous_SampleTime {
            get {
                return this.previous_SampleTimeField;
            }
            set {
                this.previous_SampleTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Current_SampleTime {
            get {
                return this.current_SampleTimeField;
            }
            set {
                this.current_SampleTimeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class MeasurementsSampleN_RSP1 {
        
        private byte alarmField;
        
        private string dataField;
        
        private string bkgField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte Alarm {
            get {
                return this.alarmField;
            }
            set {
                this.alarmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Bkg {
            get {
                return this.bkgField;
            }
            set {
                this.bkgField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class MeasurementsSampleG_RSP1 {
        
        private byte alarmField;
        
        private string dataField;
        
        private string bkgField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte Alarm {
            get {
                return this.alarmField;
            }
            set {
                this.alarmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Bkg {
            get {
                return this.bkgField;
            }
            set {
                this.bkgField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class MeasurementsSampleN_RSP2 {
        
        private byte alarmField;
        
        private string dataField;
        
        private string bkgField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte Alarm {
            get {
                return this.alarmField;
            }
            set {
                this.alarmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Bkg {
            get {
                return this.bkgField;
            }
            set {
                this.bkgField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class MeasurementsSampleG_RSP2 {
        
        private byte alarmField;
        
        private string dataField;
        
        private string bkgField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte Alarm {
            get {
                return this.alarmField;
            }
            set {
                this.alarmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Bkg {
            get {
                return this.bkgField;
            }
            set {
                this.bkgField = value;
            }
        }
    }
}
