//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4206
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

namespace L3.Cargo.Common.Xml.Annotations_1_0
{
    // 
    // This source code was auto-generated by xsd, Version=2.0.50727.3038.
    // 

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute("Annotations", Namespace = "", IsNullable = false)]
    public partial class Annotations
    {
        private AnnotationArrayItem[] itemsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Annotation", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public AnnotationArrayItem[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class AnnotationArrayItem
    {

        private double topLeftXField;

        private double topLeftYField;

        private double widthField;

        private double heightField;

        private double radiusXField;

        private double radiusYField;

        private string commentField;

        private int viewField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TopLeft.X", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double TopLeftX
        {
            get
            {
                return this.topLeftXField;
            }
            set
            {
                this.topLeftXField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TopLeft.Y", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double TopLeftY
        {
            get
            {
                return this.topLeftYField;
            }
            set
            {
                this.topLeftYField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double Width
        {
            get
            {
                return this.widthField;
            }
            set
            {
                this.widthField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double Height
        {
            get
            {
                return this.heightField;
            }
            set
            {
                this.heightField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double RadiusX
        {
            get
            {
                return this.radiusXField;
            }
            set
            {
                this.radiusXField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double RadiusY
        {
            get
            {
                return this.radiusYField;
            }
            set
            {
                this.radiusYField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Comment
        {
            get
            {
                return this.commentField;
            }
            set
            {
                this.commentField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int View
        {
            get
            {
                return this.viewField;
            }
            set
            {
                this.viewField = value;
            }
        }
    }
}