//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace L3.Cargo.Detectors.Display.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("L3.Cargo.Detectors.Display.Common.Cultures.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to connect to APCS.
        /// </summary>
        public static string APCS_CONNECTED_0 {
            get {
                return ResourceManager.GetString("APCS_CONNECTED_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad Detectors.
        /// </summary>
        public static string BAD_DETECTORS_TITLE {
            get {
                return ResourceManager.GetString("BAD_DETECTORS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calibration Control.
        /// </summary>
        public static string CALIBRATION_CONTROLS_TITLE {
            get {
                return ResourceManager.GetString("CALIBRATION_CONTROLS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calibration Running.
        /// </summary>
        public static string CALIBRATION_START_PRESSED {
            get {
                return ResourceManager.GetString("CALIBRATION_START_PRESSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Calibration.
        /// </summary>
        public static string CALIBRATION_START_UNPRESSED {
            get {
                return ResourceManager.GetString("CALIBRATION_START_UNPRESSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detectors System Information.
        /// </summary>
        public static string COMPLETE_INFO_TITLE {
            get {
                return ResourceManager.GetString("COMPLETE_INFO_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to connect to Detectors..
        /// </summary>
        public static string DETECTORS_CONNECTED_0 {
            get {
                return ResourceManager.GetString("DETECTORS_CONNECTED_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Real Time Display.
        /// </summary>
        public static string DETECTORS_REAL_TIME_DISPLAY_TITLE {
            get {
                return ResourceManager.GetString("DETECTORS_REAL_TIME_DISPLAY_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All detectors are good.
        /// </summary>
        public static string DETECTORS_STATUS_0 {
            get {
                return ResourceManager.GetString("DETECTORS_STATUS_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning Bad detectors found.
        /// </summary>
        public static string DETECTORS_STATUS_1 {
            get {
                return ResourceManager.GetString("DETECTORS_STATUS_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Bad detectors found.
        /// </summary>
        public static string DETECTORS_STATUS_2 {
            get {
                return ResourceManager.GetString("DETECTORS_STATUS_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calibration data not found.
        /// </summary>
        public static string DETECTORS_STATUS_3 {
            get {
                return ResourceManager.GetString("DETECTORS_STATUS_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detectors System Errors.
        /// </summary>
        public static string ERROR_MESSAGES_TITLE {
            get {
                return ResourceManager.GetString("ERROR_MESSAGES_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display information about the status of the Detectors system..
        /// </summary>
        public static string INFO_BUTTON_DESCRIPTION {
            get {
                return ResourceManager.GetString("INFO_BUTTON_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detectors Controller.
        /// </summary>
        public static string INFO_BUTTON_TITLE {
            get {
                return ResourceManager.GetString("INFO_BUTTON_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detectors Status.
        /// </summary>
        public static string STATUSBAR_TITLE {
            get {
                return ResourceManager.GetString("STATUSBAR_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNKNOWN ERROR.
        /// </summary>
        public static string UNKNOWN_RESOURCE {
            get {
                return ResourceManager.GetString("UNKNOWN_RESOURCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detectors System Warnings.
        /// </summary>
        public static string WARNING_MESSAGES_TITLE {
            get {
                return ResourceManager.GetString("WARNING_MESSAGES_TITLE", resourceCulture);
            }
        }
    }
}
