//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace L3.Cargo.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("L3.Cargo.Common.Cultures.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Criteria.
        /// </summary>
        public static string AddCriteria {
            get {
                return ResourceManager.GetString("AddCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarms.
        /// </summary>
        public static string Alarms {
            get {
                return ResourceManager.GetString("Alarms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysis History.
        /// </summary>
        public static string AnalysisHistory {
            get {
                return ResourceManager.GetString("AnalysisHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysis Time:.
        /// </summary>
        public static string AnalysisTime_Colon {
            get {
                return ResourceManager.GetString("AnalysisTime_Colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyst.
        /// </summary>
        public static string Analyst {
            get {
                return ResourceManager.GetString("Analyst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyst Comment.
        /// </summary>
        public static string AnalystComment {
            get {
                return ResourceManager.GetString("AnalystComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annotation.
        /// </summary>
        public static string Annotation {
            get {
                return ResourceManager.GetString("Annotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annotations.
        /// </summary>
        public static string Annotations {
            get {
                return ResourceManager.GetString("Annotations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anomaly Identified.
        /// </summary>
        public static string AnomalyIdentified {
            get {
                return ResourceManager.GetString("AnomalyIdentified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive Cases.
        /// </summary>
        public static string ArchiveCases {
            get {
                return ResourceManager.GetString("ArchiveCases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area.
        /// </summary>
        public static string Area {
            get {
                return ResourceManager.GetString("Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area of Interest.
        /// </summary>
        public static string AreaOfInterest {
            get {
                return ResourceManager.GetString("AreaOfInterest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment File.
        /// </summary>
        public static string AttachmentFile {
            get {
                return ResourceManager.GetString("AttachmentFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment Type.
        /// </summary>
        public static string AttachmentType {
            get {
                return ResourceManager.GetString("AttachmentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Select.
        /// </summary>
        public static string AutoSelect {
            get {
                return ResourceManager.GetString("AutoSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Images.
        /// </summary>
        public static string AvailableImages {
            get {
                return ResourceManager.GetString("AvailableImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Location:.
        /// </summary>
        public static string BaseLocation_Colon {
            get {
                return ResourceManager.GetString("BaseLocation_Colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch Number:.
        /// </summary>
        public static string BatchNumber_Colon {
            get {
                return ResourceManager.GetString("BatchNumber_Colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BD:.
        /// </summary>
        public static string BD_Colon {
            get {
                return ResourceManager.GetString("BD_Colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blur Effect.
        /// </summary>
        public static string BlurEffect {
            get {
                return ResourceManager.GetString("BlurEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buffer.
        /// </summary>
        public static string Buffer {
            get {
                return ResourceManager.GetString("Buffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build Date:.
        /// </summary>
        public static string BuildDate_Colon {
            get {
                return ResourceManager.GetString("BuildDate_Colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build Number:.
        /// </summary>
        public static string BuildNumber_Colon {
            get {
                return ResourceManager.GetString("BuildNumber_Colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bundle:.
        /// </summary>
        public static string Bundle_Colon {
            get {
                return ResourceManager.GetString("Bundle_Colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case Attachments.
        /// </summary>
        public static string CaseAttachments {
            get {
                return ResourceManager.GetString("CaseAttachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case Id.
        /// </summary>
        public static string CaseId {
            get {
                return ResourceManager.GetString("CaseId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case Id:.
        /// </summary>
        public static string CaseId_Colon {
            get {
                return ResourceManager.GetString("CaseId_Colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case Info.
        /// </summary>
        public static string CaseInfo {
            get {
                return ResourceManager.GetString("CaseInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case Information.
        /// </summary>
        public static string CaseInformation {
            get {
                return ResourceManager.GetString("CaseInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case Information Print Options.
        /// </summary>
        public static string CaseInformationPrintOptions {
            get {
                return ResourceManager.GetString("CaseInformationPrintOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cases.
        /// </summary>
        public static string Cases {
            get {
                return ResourceManager.GetString("Cases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case Source Name.
        /// </summary>
        public static string CaseSourceName {
            get {
                return ResourceManager.GetString("CaseSourceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caution.
        /// </summary>
        public static string Caution {
            get {
                return ResourceManager.GetString("Caution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chrome.
        /// </summary>
        public static string Chrome {
            get {
                return ResourceManager.GetString("Chrome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to chromey.
        /// </summary>
        public static string chromey {
            get {
                return ResourceManager.GetString("chromey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClearCase.
        /// </summary>
        public static string ClearCase {
            get {
                return ResourceManager.GetString("ClearCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Screen.
        /// </summary>
        public static string ClearScreen {
            get {
                return ResourceManager.GetString("ClearScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Tab.
        /// </summary>
        public static string CloseTab {
            get {
                return ResourceManager.GetString("CloseTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code:.
        /// </summary>
        public static string Code_Colon {
            get {
                return ResourceManager.GetString("Code_Colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Background.
        /// </summary>
        public static string ColorBackground {
            get {
                return ResourceManager.GetString("ColorBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment:.
        /// </summary>
        public static string Comment_Colon {
            get {
                return ResourceManager.GetString("Comment_Colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Container Information.
        /// </summary>
        public static string ContainerInformation {
            get {
                return ResourceManager.GetString("ContainerInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conveyance Information.
        /// </summary>
        public static string ConveyanceInformation {
            get {
                return ResourceManager.GetString("ConveyanceInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy (Ctrl+C).
        /// </summary>
        public static string Copy_CtrlC {
            get {
                return ResourceManager.GetString("Copy_CtrlC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Report.
        /// </summary>
        public static string CreateReport {
            get {
                return ResourceManager.GetString("CreateReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Time.
        /// </summary>
        public static string CreateTime {
            get {
                return ResourceManager.GetString("CreateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Time:.
        /// </summary>
        public static string CreateTime_Colon {
            get {
                return ResourceManager.GetString("CreateTime_Colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl.
        /// </summary>
        public static string Ctrl {
            get {
                return ResourceManager.GetString("Ctrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D:.
        /// </summary>
        public static string D_Colon {
            get {
                return ResourceManager.GetString("D_Colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damaged Bundle.
        /// </summary>
        public static string DamagedBundle {
            get {
                return ResourceManager.GetString("DamagedBundle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decision.
        /// </summary>
        public static string Decision {
            get {
                return ResourceManager.GetString("Decision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decision:.
        /// </summary>
        public static string Decision_Colon {
            get {
                return ResourceManager.GetString("Decision_Colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrease the size of the content (Ctrl -).
        /// </summary>
        public static string DecreaseTheSizeOfTheContent_CtrlMinus {
            get {
                return ResourceManager.GetString("DecreaseTheSizeOfTheContent_CtrlMinus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Criteria.
        /// </summary>
        public static string DeleteCriteria {
            get {
                return ResourceManager.GetString("DeleteCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Density Alarm Threshold.
        /// </summary>
        public static string DensityAlarm {
            get {
                return ResourceManager.GetString("DensityAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deselect All.
        /// </summary>
        public static string DeselectAll {
            get {
                return ResourceManager.GetString("DeselectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DFC Status.
        /// </summary>
        public static string DFCStatus {
            get {
                return ResourceManager.GetString("DFCStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dual Energy.
        /// </summary>
        public static string DualEnergy {
            get {
                return ResourceManager.GetString("DualEnergy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edge Enhancement.
        /// </summary>
        public static string EdgeEnhancement {
            get {
                return ResourceManager.GetString("EdgeEnhancement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Container Id.
        /// </summary>
        public static string EditContainerId {
            get {
                return ResourceManager.GetString("EditContainerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Snapshots.
        /// </summary>
        public static string EditSnapshots {
            get {
                return ResourceManager.GetString("EditSnapshots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ellipse.
        /// </summary>
        public static string Ellipse {
            get {
                return ResourceManager.GetString("Ellipse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The case requested is currently in use..
        /// </summary>
        public static string Error_CaseCurrentlyInUse {
            get {
                return ResourceManager.GetString("Error_CaseCurrentlyInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified Case does not exist in the Case List..
        /// </summary>
        public static string Error_CaseDoesNotExist {
            get {
                return ResourceManager.GetString("Error_CaseDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The case id is empty, null, or invalid..
        /// </summary>
        public static string Error_CaseIdInvalid {
            get {
                return ResourceManager.GetString("Error_CaseIdInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The list of available cases is currently not available..
        /// </summary>
        public static string Error_CaseListNotAvailable {
            get {
                return ResourceManager.GetString("Error_CaseListNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Workstation does not have access to this case..
        /// </summary>
        public static string Error_CaseNotAccessible {
            get {
                return ResourceManager.GetString("Error_CaseNotAccessible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case is not listed in the case list:.
        /// </summary>
        public static string Error_CaseNotListed {
            get {
                return ResourceManager.GetString("Error_CaseNotListed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML file version does not match schema..
        /// </summary>
        public static string Error_CaseVersionMismatch {
            get {
                return ResourceManager.GetString("Error_CaseVersionMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The filename length is 0, please provide a valid filename.
        /// </summary>
        public static string Error_FilenameEmpty {
            get {
                return ResourceManager.GetString("Error_FilenameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The function being called is invalid or has not been implemented..
        /// </summary>
        public static string Error_InvalidFunction {
            get {
                return ResourceManager.GetString("Error_InvalidFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username and password are incorrect.  Please contact your system administrator..
        /// </summary>
        public static string Error_InvalidLogin {
            get {
                return ResourceManager.GetString("Error_InvalidLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case Request not processed for load balance reasons..
        /// </summary>
        public static string Error_LoadBalanceDelayCaseRequirements {
            get {
                return ResourceManager.GetString("Error_LoadBalanceDelayCaseRequirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are currently no available archive case sources.
        /// </summary>
        public static string Error_NoArchiveSources {
            get {
                return ResourceManager.GetString("Error_NoArchiveSources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are currently no available pending cases..
        /// </summary>
        public static string Error_NoLiveCase {
            get {
                return ResourceManager.GetString("Error_NoLiveCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are currently no available pending case sources.
        /// </summary>
        public static string Error_NoLiveSources {
            get {
                return ResourceManager.GetString("Error_NoLiveSources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No user profile could be found.  Please contact your system administrator..
        /// </summary>
        public static string Error_NoUserProfile {
            get {
                return ResourceManager.GetString("Error_NoUserProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The pending case is currently being shown and must be cleared before a new one can be selected.
        /// </summary>
        public static string Error_OnePendingCaseOnly {
            get {
                return ResourceManager.GetString("Error_OnePendingCaseOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The case source is no longer available..
        /// </summary>
        public static string Error_SourceNotAvailable {
            get {
                return ResourceManager.GetString("Error_SourceNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The select case source Type is unknown..
        /// </summary>
        public static string Error_SourceTypeUnknown {
            get {
                return ResourceManager.GetString("Error_SourceTypeUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Dll was unable to create a thumbnail from the PXE file passed..
        /// </summary>
        public static string Error_ThumbnailCreateFail {
            get {
                return ResourceManager.GetString("Error_ThumbnailCreateFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existing Macros.
        /// </summary>
        public static string ExistingMacros {
            get {
                return ResourceManager.GetString("ExistingMacros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters.
        /// </summary>
        public static string Filters {
            get {
                return ResourceManager.GetString("Filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fit To Screen.
        /// </summary>
        public static string FitToScreen {
            get {
                return ResourceManager.GetString("FitToScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flight Number.
        /// </summary>
        public static string FlightNumber {
            get {
                return ResourceManager.GetString("FlightNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frag #.
        /// </summary>
        public static string Frag_Num {
            get {
                return ResourceManager.GetString("Frag_Num", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fragment Analysis.
        /// </summary>
        public static string FragmentAnalysis {
            get {
                return ResourceManager.GetString("FragmentAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fragment Data.
        /// </summary>
        public static string FragmentData {
            get {
                return ResourceManager.GetString("FragmentData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fragment Marks.
        /// </summary>
        public static string FragmentMarks {
            get {
                return ResourceManager.GetString("FragmentMarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FTIImage.
        /// </summary>
        public static string FTIImage {
            get {
                return ResourceManager.GetString("FTIImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gamma/Neutron Profile.
        /// </summary>
        public static string GammaNeutronProfile {
            get {
                return ResourceManager.GetString("GammaNeutronProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give Decision.
        /// </summary>
        public static string GiveDecision {
            get {
                return ResourceManager.GetString("GiveDecision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gray Background.
        /// </summary>
        public static string GrayBackground {
            get {
                return ResourceManager.GetString("GrayBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height:.
        /// </summary>
        public static string Height_Colon {
            get {
                return ResourceManager.GetString("Height_Colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Annotation.
        /// </summary>
        public static string HideAnnotation {
            get {
                return ResourceManager.GetString("HideAnnotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Marks.
        /// </summary>
        public static string HideMarks {
            get {
                return ResourceManager.GetString("HideMarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Measurements.
        /// </summary>
        public static string HideMeasurements {
            get {
                return ResourceManager.GetString("HideMeasurements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Density Cargo.
        /// </summary>
        public static string HighDensityCargo {
            get {
                return ResourceManager.GetString("HighDensityCargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Energy.
        /// </summary>
        public static string HighEnergy {
            get {
                return ResourceManager.GetString("HighEnergy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Histogram.
        /// </summary>
        public static string Histogram {
            get {
                return ResourceManager.GetString("Histogram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id:.
        /// </summary>
        public static string Id_Colon {
            get {
                return ResourceManager.GetString("Id_Colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image History.
        /// </summary>
        public static string ImageHistory {
            get {
                return ResourceManager.GetString("ImageHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inconclusive.
        /// </summary>
        public static string Inconclusive {
            get {
                return ResourceManager.GetString("Inconclusive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase the size of the content (Ctrl +).
        /// </summary>
        public static string IncreaseTheSizeOfTheContent_CtrlPlus {
            get {
                return ResourceManager.GetString("IncreaseTheSizeOfTheContent_CtrlPlus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inorganic Strip.
        /// </summary>
        public static string InorganicStrip {
            get {
                return ResourceManager.GetString("InorganicStrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invert.
        /// </summary>
        public static string Invert {
            get {
                return ResourceManager.GetString("Invert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude:.
        /// </summary>
        public static string Latitude_Colon {
            get {
                return ResourceManager.GetString("Latitude_Colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Information.
        /// </summary>
        public static string LocationInformation {
            get {
                return ResourceManager.GetString("LocationInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude:.
        /// </summary>
        public static string Longitude_Colon {
            get {
                return ResourceManager.GetString("Longitude_Colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low Density Cargo.
        /// </summary>
        public static string LowDensityCargo {
            get {
                return ResourceManager.GetString("LowDensityCargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low Energy.
        /// </summary>
        public static string LowEnergy {
            get {
                return ResourceManager.GetString("LowEnergy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Macro Name.
        /// </summary>
        public static string MacroName {
            get {
                return ResourceManager.GetString("MacroName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magnifier.
        /// </summary>
        public static string Magnifier {
            get {
                return ResourceManager.GetString("Magnifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manifest.
        /// </summary>
        public static string Manifest {
            get {
                return ResourceManager.GetString("Manifest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manifests.
        /// </summary>
        public static string Manifests {
            get {
                return ResourceManager.GetString("Manifests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual Inspection.
        /// </summary>
        public static string ManualInspection {
            get {
                return ResourceManager.GetString("ManualInspection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MapX.
        /// </summary>
        public static string MapX {
            get {
                return ResourceManager.GetString("MapX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum number of annotations is reached, please remove to add another one.
        /// </summary>
        public static string MaxAnnotationErrorMessage {
            get {
                return ResourceManager.GetString("MaxAnnotationErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum:.
        /// </summary>
        public static string Maximum_Colon {
            get {
                return ResourceManager.GetString("Maximum_Colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max number of macros have been met.\nPlease replace one of the macros..
        /// </summary>
        public static string MaxNumberOfMacrosHaveBeenMetPleaseReplaceOneOfTheMacros {
            get {
                return ResourceManager.GetString("MaxNumberOfMacrosHaveBeenMetPleaseReplaceOneOfTheMacros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mean Value:.
        /// </summary>
        public static string MeanValue_Colon {
            get {
                return ResourceManager.GetString("MeanValue_Colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measurements.
        /// </summary>
        public static string Measurements {
            get {
                return ResourceManager.GetString("Measurements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metal Strip.
        /// </summary>
        public static string MetalStrip {
            get {
                return ResourceManager.GetString("MetalStrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum:.
        /// </summary>
        public static string Minimum_Colon {
            get {
                return ResourceManager.GetString("Minimum_Colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        public static string Minus_Sign {
            get {
                return ResourceManager.GetString("Minus_Sign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mission:.
        /// </summary>
        public static string Mission_Colon {
            get {
                return ResourceManager.GetString("Mission_Colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Needs Rescan.
        /// </summary>
        public static string NeedsRescan {
            get {
                return ResourceManager.GetString("NeedsRescan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to newchrome.
        /// </summary>
        public static string newchrome {
            get {
                return ResourceManager.GetString("newchrome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Image.
        /// </summary>
        public static string NoImage {
            get {
                return ResourceManager.GetString("NoImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Options Available.
        /// </summary>
        public static string NoOptionsAvailable {
            get {
                return ResourceManager.GetString("NoOptionsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NORMAlarms.
        /// </summary>
        public static string NORMAlarms {
            get {
                return ResourceManager.GetString("NORMAlarms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal Density Cargo.
        /// </summary>
        public static string NormalDensityCargo {
            get {
                return ResourceManager.GetString("NormalDensityCargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Source Selected.
        /// </summary>
        public static string NoSourceSelected {
            get {
                return ResourceManager.GetString("NoSourceSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Applicable.
        /// </summary>
        public static string NotApplicable {
            get {
                return ResourceManager.GetString("NotApplicable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes:.
        /// </summary>
        public static string Notes_Colon {
            get {
                return ResourceManager.GetString("Notes_Colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuclear Isotope Analysis.
        /// </summary>
        public static string NuclearIsotopeAnalysis {
            get {
                return ResourceManager.GetString("NuclearIsotopeAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object ID.
        /// </summary>
        public static string ObjectId {
            get {
                return ResourceManager.GetString("ObjectId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OCR Image.
        /// </summary>
        public static string OCRImage {
            get {
                return ResourceManager.GetString("OCRImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OCR Images.
        /// </summary>
        public static string OCRImages {
            get {
                return ResourceManager.GetString("OCRImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OCR Images Print Options.
        /// </summary>
        public static string OCRImagesPrintOptions {
            get {
                return ResourceManager.GetString("OCRImagesPrintOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1:1.
        /// </summary>
        public static string One_Colon_One {
            get {
                return ResourceManager.GetString("One_Colon_One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100% (Ctrl+1).
        /// </summary>
        public static string OneHundredPercent_Ctrl1 {
            get {
                return ResourceManager.GetString("OneHundredPercent_Ctrl1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open as comparison?.
        /// </summary>
        public static string OpenAsComparison_Question {
            get {
                return ResourceManager.GetString("OpenAsComparison_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organic Strip.
        /// </summary>
        public static string OrganicStrip {
            get {
                return ResourceManager.GetString("OrganicStrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original.
        /// </summary>
        public static string Original {
            get {
                return ResourceManager.GetString("Original", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Others.
        /// </summary>
        public static string Others {
            get {
                return ResourceManager.GetString("Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page 1 of 2.
        /// </summary>
        public static string PageOfPage {
            get {
                return ResourceManager.GetString("PageOfPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Width (Ctrl+2).
        /// </summary>
        public static string PageWidth_Ctrl2 {
            get {
                return ResourceManager.GetString("PageWidth_Ctrl2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pan and Zoom.
        /// </summary>
        public static string PanAndZoom {
            get {
                return ResourceManager.GetString("PanAndZoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parrot.
        /// </summary>
        public static string Parrot {
            get {
                return ResourceManager.GetString("Parrot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        public static string Password_Colon {
            get {
                return ResourceManager.GetString("Password_Colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Cases.
        /// </summary>
        public static string PendingCases {
            get {
                return ResourceManager.GetString("PendingCases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Physical Deviation.
        /// </summary>
        public static string PhysicalDeviation {
            get {
                return ResourceManager.GetString("PhysicalDeviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a name for the macro.
        /// </summary>
        public static string PleaseEnterANameForTheMacro {
            get {
                return ResourceManager.GetString("PleaseEnterANameForTheMacro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +.
        /// </summary>
        public static string Plus_Sign {
            get {
                return ResourceManager.GetString("Plus_Sign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position A.
        /// </summary>
        public static string PositionA {
            get {
                return ResourceManager.GetString("PositionA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position B.
        /// </summary>
        public static string PositionB {
            get {
                return ResourceManager.GetString("PositionB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presets.
        /// </summary>
        public static string Presets {
            get {
                return ResourceManager.GetString("Presets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print (Ctrl+P).
        /// </summary>
        public static string Print_CtrlP {
            get {
                return ResourceManager.GetString("Print_CtrlP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Time:.
        /// </summary>
        public static string PrintTime_Colon {
            get {
                return ResourceManager.GetString("PrintTime_Colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project:.
        /// </summary>
        public static string Project_Colon {
            get {
                return ResourceManager.GetString("Project_Colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PseudoColor.
        /// </summary>
        public static string PseudoColor {
            get {
                return ResourceManager.GetString("PseudoColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pseudo Color Mappings.
        /// </summary>
        public static string PseudoColorMappings {
            get {
                return ResourceManager.GetString("PseudoColorMappings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quadmat.
        /// </summary>
        public static string Quadmat {
            get {
                return ResourceManager.GetString("Quadmat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radiation Detection Print Options.
        /// </summary>
        public static string RadiationDetectionPrintOptions {
            get {
                return ResourceManager.GetString("RadiationDetectionPrintOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radiation Detector Data.
        /// </summary>
        public static string RadiationDetectorData {
            get {
                return ResourceManager.GetString("RadiationDetectorData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rainbow.
        /// </summary>
        public static string rainbow {
            get {
                return ResourceManager.GetString("rainbow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rainbow2.
        /// </summary>
        public static string rainbow2 {
            get {
                return ResourceManager.GetString("rainbow2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range:.
        /// </summary>
        public static string Range_Colon {
            get {
                return ResourceManager.GetString("Range_Colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reapply.
        /// </summary>
        public static string Reapply {
            get {
                return ResourceManager.GetString("Reapply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason.
        /// </summary>
        public static string Reason {
            get {
                return ResourceManager.GetString("Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason:.
        /// </summary>
        public static string Reason_Colon {
            get {
                return ResourceManager.GetString("Reason_Colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rectangle.
        /// </summary>
        public static string Rectangle {
            get {
                return ResourceManager.GetString("Rectangle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register View.
        /// </summary>
        public static string RegisterView {
            get {
                return ResourceManager.GetString("RegisterView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject.
        /// </summary>
        public static string Reject {
            get {
                return ResourceManager.GetString("Reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Background.
        /// </summary>
        public static string RemoveBackground {
            get {
                return ResourceManager.GetString("RemoveBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Markings.
        /// </summary>
        public static string RemoveMarkings {
            get {
                return ResourceManager.GetString("RemoveMarkings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Generation.
        /// </summary>
        public static string ReportGeneration {
            get {
                return ResourceManager.GetString("ReportGeneration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Default.
        /// </summary>
        public static string ResetDefaults {
            get {
                return ResourceManager.GetString("ResetDefaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Uniformity.
        /// </summary>
        public static string ResetUniformity {
            get {
                return ResourceManager.GetString("ResetUniformity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        public static string Result {
            get {
                return ResourceManager.GetString("Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        public static string Results {
            get {
                return ResourceManager.GetString("Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-usable.
        /// </summary>
        public static string Reusable {
            get {
                return ResourceManager.GetString("Reusable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Image As....
        /// </summary>
        public static string SaveImageAs_Ellipsis {
            get {
                return ResourceManager.GetString("SaveImageAs_Ellipsis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan Container Id.
        /// </summary>
        public static string ScanContainerId {
            get {
                return ResourceManager.GetString("ScanContainerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan Container Information.
        /// </summary>
        public static string ScanContainerInformation {
            get {
                return ResourceManager.GetString("ScanContainerInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan Conveyance Information.
        /// </summary>
        public static string ScanConveyanceInformation {
            get {
                return ResourceManager.GetString("ScanConveyanceInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan Location Information.
        /// </summary>
        public static string ScanLocationInformation {
            get {
                return ResourceManager.GetString("ScanLocationInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scans.
        /// </summary>
        public static string Scans {
            get {
                return ResourceManager.GetString("Scans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan Time:.
        /// </summary>
        public static string ScanTime_Colon {
            get {
                return ResourceManager.GetString("ScanTime_Colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan Type Information.
        /// </summary>
        public static string ScanTypeInformation {
            get {
                return ResourceManager.GetString("ScanTypeInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        public static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an attachment to remove from the newly added attachment list.
        /// </summary>
        public static string SelectAnAttachmentToRemove {
            get {
                return ResourceManager.GetString("SelectAnAttachmentToRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected case is already being displayed.
        /// </summary>
        public static string SelectedCaseIsAlreadyBeingDisplayed {
            get {
                return ResourceManager.GetString("SelectedCaseIsAlreadyBeingDisplayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence Number:.
        /// </summary>
        public static string SequenceNumber_Colon {
            get {
                return ResourceManager.GetString("SequenceNumber_Colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set.
        /// </summary>
        public static string Set {
            get {
                return ResourceManager.GetString("Set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup.
        /// </summary>
        public static string Setup {
            get {
                return ResourceManager.GetString("Setup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shape.
        /// </summary>
        public static string Shape {
            get {
                return ResourceManager.GetString("Shape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sharpen.
        /// </summary>
        public static string Sharpen {
            get {
                return ResourceManager.GetString("Sharpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift.
        /// </summary>
        public static string Shift {
            get {
                return ResourceManager.GetString("Shift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Annotation.
        /// </summary>
        public static string ShowAnnotation {
            get {
                return ResourceManager.GetString("ShowAnnotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Marks.
        /// </summary>
        public static string ShowMarks {
            get {
                return ResourceManager.GetString("ShowMarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Measurements.
        /// </summary>
        public static string ShowMeasurements {
            get {
                return ResourceManager.GetString("ShowMeasurements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site ID.
        /// </summary>
        public static string SiteId {
            get {
                return ResourceManager.GetString("SiteId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Id:.
        /// </summary>
        public static string SiteId_Colon {
            get {
                return ResourceManager.GetString("SiteId_Colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        public static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source:.
        /// </summary>
        public static string Source_Colon {
            get {
                return ResourceManager.GetString("Source_Colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Station Type:.
        /// </summary>
        public static string StationType_Colon {
            get {
                return ResourceManager.GetString("StationType_Colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STD:.
        /// </summary>
        public static string STD_Colon {
            get {
                return ResourceManager.GetString("STD_Colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STD %.
        /// </summary>
        public static string STD_Percent {
            get {
                return ResourceManager.GetString("STD_Percent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step.
        /// </summary>
        public static string Step {
            get {
                return ResourceManager.GetString("Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Information.
        /// </summary>
        public static string SystemInformation {
            get {
                return ResourceManager.GetString("SystemInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TDSResultFile.
        /// </summary>
        public static string TDSResultFile {
            get {
                return ResourceManager.GetString("TDSResultFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tentative.
        /// </summary>
        public static string Tentative {
            get {
                return ResourceManager.GetString("Tentative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to test1.
        /// </summary>
        public static string test1 {
            get {
                return ResourceManager.GetString("test1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to test2.
        /// </summary>
        public static string test2 {
            get {
                return ResourceManager.GetString("test2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to test3.
        /// </summary>
        public static string test3 {
            get {
                return ResourceManager.GetString("test3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to test4.
        /// </summary>
        public static string test4 {
            get {
                return ResourceManager.GetString("test4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to test5.
        /// </summary>
        public static string test5 {
            get {
                return ResourceManager.GetString("test5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to test6.
        /// </summary>
        public static string test6 {
            get {
                return ResourceManager.GetString("test6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to test7.
        /// </summary>
        public static string test7 {
            get {
                return ResourceManager.GetString("test7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to test8.
        /// </summary>
        public static string test8 {
            get {
                return ResourceManager.GetString("test8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to test9.
        /// </summary>
        public static string test9 {
            get {
                return ResourceManager.GetString("test9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Name:.
        /// </summary>
        public static string TestName_Colon {
            get {
                return ResourceManager.GetString("TestName_Colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too Complex.
        /// </summary>
        public static string TooComplex {
            get {
                return ResourceManager.GetString("TooComplex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too Dense.
        /// </summary>
        public static string TooDense {
            get {
                return ResourceManager.GetString("TooDense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Weight:.
        /// </summary>
        public static string TotalWeight_Colon {
            get {
                return ResourceManager.GetString("TotalWeight_Colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trimat.
        /// </summary>
        public static string Trimat {
            get {
                return ResourceManager.GetString("Trimat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two Pages (Ctrl+4).
        /// </summary>
        public static string TwoPages_Ctrl4 {
            get {
                return ResourceManager.GetString("TwoPages_Ctrl4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type:.
        /// </summary>
        public static string Type_Colon {
            get {
                return ResourceManager.GetString("Type_Colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ULD Number.
        /// </summary>
        public static string ULDNumber {
            get {
                return ResourceManager.GetString("ULDNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ULD Number:.
        /// </summary>
        public static string ULDNumber_Colon {
            get {
                return ResourceManager.GetString("ULDNumber_Colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uniformity.
        /// </summary>
        public static string Uniformity {
            get {
                return ResourceManager.GetString("Uniformity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uniformity Analysis Graph.
        /// </summary>
        public static string UniformityAnalysisGraph {
            get {
                return ResourceManager.GetString("UniformityAnalysisGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uniformity Results.
        /// </summary>
        public static string UniformityResults {
            get {
                return ResourceManager.GetString("UniformityResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to untitled2.
        /// </summary>
        public static string untitled2 {
            get {
                return ResourceManager.GetString("untitled2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Container ID.
        /// </summary>
        public static string UpdateContainerId {
            get {
                return ResourceManager.GetString("UpdateContainerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Time.
        /// </summary>
        public static string UpdateTime {
            get {
                return ResourceManager.GetString("UpdateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User:.
        /// </summary>
        public static string User_Colon {
            get {
                return ResourceManager.GetString("User_Colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Macros.
        /// </summary>
        public static string UserMacros {
            get {
                return ResourceManager.GetString("UserMacros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username:.
        /// </summary>
        public static string Username_Colon {
            get {
                return ResourceManager.GetString("Username_Colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value:.
        /// </summary>
        public static string Value_Colon {
            get {
                return ResourceManager.GetString("Value_Colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to value for MinRange cannot be less than 0.
        /// </summary>
        public static string ValueForMinRangeCannotBeLessThan0 {
            get {
                return ResourceManager.GetString("ValueForMinRangeCannotBeLessThan0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:.
        /// </summary>
        public static string Version_Colon {
            get {
                return ResourceManager.GetString("Version_Colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View 1.
        /// </summary>
        public static string View1 {
            get {
                return ResourceManager.GetString("View1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View History.
        /// </summary>
        public static string ViewHistory {
            get {
                return ResourceManager.GetString("ViewHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warnings.
        /// </summary>
        public static string Warnings {
            get {
                return ResourceManager.GetString("Warnings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight:.
        /// </summary>
        public static string Weight_Colon {
            get {
                return ResourceManager.GetString("Weight_Colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whole Page (Ctrl+3).
        /// </summary>
        public static string WholePage_Ctrl3 {
            get {
                return ResourceManager.GetString("WholePage_Ctrl3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width:.
        /// </summary>
        public static string Width_Colon {
            get {
                return ResourceManager.GetString("Width_Colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X:.
        /// </summary>
        public static string X_Colon {
            get {
                return ResourceManager.GetString("X_Colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xchrome.
        /// </summary>
        public static string xchrome {
            get {
                return ResourceManager.GetString("xchrome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xray Image.
        /// </summary>
        public static string XRayImage {
            get {
                return ResourceManager.GetString("XRayImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xray Image Print Options.
        /// </summary>
        public static string XrayImagePrintOptions {
            get {
                return ResourceManager.GetString("XrayImagePrintOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XRayPlugin.
        /// </summary>
        public static string XRayPlugin {
            get {
                return ResourceManager.GetString("XRayPlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XRayPlugin-View0.
        /// </summary>
        public static string XRayPluginView0 {
            get {
                return ResourceManager.GetString("XRayPluginView0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XRayPlugin-View1.
        /// </summary>
        public static string XRayPluginView1 {
            get {
                return ResourceManager.GetString("XRayPluginView1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y:.
        /// </summary>
        public static string Y_Colon {
            get {
                return ResourceManager.GetString("Y_Colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom:.
        /// </summary>
        public static string Zoom_Colon {
            get {
                return ResourceManager.GetString("Zoom_Colon", resourceCulture);
            }
        }
    }
}
