//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace L3.Cargo.Scan.Display.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("L3.Cargo.Scan.Display.Common.Cultures.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan.
        /// </summary>
        public static string CALIBRATION_SCAN_0 {
            get {
                return ResourceManager.GetString("CALIBRATION_SCAN_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calibration.
        /// </summary>
        public static string CALIBRATION_SCAN_1 {
            get {
                return ResourceManager.GetString("CALIBRATION_SCAN_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set to Calibration Mode.
        /// </summary>
        public static string CALIBRATION_SCAN_DISABLED {
            get {
                return ResourceManager.GetString("CALIBRATION_SCAN_DISABLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set to Scan Mode.
        /// </summary>
        public static string CALIBRATION_SCAN_ENABLED {
            get {
                return ResourceManager.GetString("CALIBRATION_SCAN_ENABLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan Type.
        /// </summary>
        public static string CALIBRATION_SCAN_TITLE {
            get {
                return ResourceManager.GetString("CALIBRATION_SCAN_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready to perform calibration.
        /// </summary>
        public static string CALIBRATION_STATE_0 {
            get {
                return ResourceManager.GetString("CALIBRATION_STATE_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not ready to perform calibration.
        /// </summary>
        public static string CALIBRATION_STATE_1 {
            get {
                return ResourceManager.GetString("CALIBRATION_STATE_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performing dark data calibration.
        /// </summary>
        public static string CALIBRATION_STATE_10 {
            get {
                return ResourceManager.GetString("CALIBRATION_STATE_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed dark data calibration.
        /// </summary>
        public static string CALIBRATION_STATE_11 {
            get {
                return ResourceManager.GetString("CALIBRATION_STATE_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performing low dose calibration.
        /// </summary>
        public static string CALIBRATION_STATE_12 {
            get {
                return ResourceManager.GetString("CALIBRATION_STATE_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed low dose calibration.
        /// </summary>
        public static string CALIBRATION_STATE_13 {
            get {
                return ResourceManager.GetString("CALIBRATION_STATE_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calibration has failed..
        /// </summary>
        public static string CALIBRATION_STATE_2 {
            get {
                return ResourceManager.GetString("CALIBRATION_STATE_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performing high energy calibration.
        /// </summary>
        public static string CALIBRATION_STATE_3 {
            get {
                return ResourceManager.GetString("CALIBRATION_STATE_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed high energy calibration.
        /// </summary>
        public static string CALIBRATION_STATE_4 {
            get {
                return ResourceManager.GetString("CALIBRATION_STATE_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performing low energy calibration.
        /// </summary>
        public static string CALIBRATION_STATE_5 {
            get {
                return ResourceManager.GetString("CALIBRATION_STATE_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed low energy calibration.
        /// </summary>
        public static string CALIBRATION_STATE_6 {
            get {
                return ResourceManager.GetString("CALIBRATION_STATE_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performing dual energy calibration.
        /// </summary>
        public static string CALIBRATION_STATE_7 {
            get {
                return ResourceManager.GetString("CALIBRATION_STATE_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed dual energy calibration.
        /// </summary>
        public static string CALIBRATION_STATE_8 {
            get {
                return ResourceManager.GetString("CALIBRATION_STATE_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calibrations has successfully completed.
        /// </summary>
        public static string CALIBRATION_STATE_9 {
            get {
                return ResourceManager.GetString("CALIBRATION_STATE_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calibration State.
        /// </summary>
        public static string CALIBRATION_STATE_TITLE {
            get {
                return ResourceManager.GetString("CALIBRATION_STATE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Remote.
        /// </summary>
        public static string CLICKER_DISABLE {
            get {
                return ResourceManager.GetString("CLICKER_DISABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Remote.
        /// </summary>
        public static string CLICKER_ENABLE {
            get {
                return ResourceManager.GetString("CLICKER_ENABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Marshall Remote.
        /// </summary>
        public static string CLICKER_ENABLE_TITLE {
            get {
                return ResourceManager.GetString("CLICKER_ENABLE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan System Errors.
        /// </summary>
        public static string ERROR_MESSAGES_TITLE {
            get {
                return ResourceManager.GetString("ERROR_MESSAGES_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display all information about the Scan system.
        /// </summary>
        public static string INFO_BUTTON_DESCRIPTION {
            get {
                return ResourceManager.GetString("INFO_BUTTON_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan System.
        /// </summary>
        public static string INFO_BUTTON_TITLE {
            get {
                return ResourceManager.GetString("INFO_BUTTON_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prevent Scanning.
        /// </summary>
        public static string SCAN_AREA_CLEAR_0 {
            get {
                return ResourceManager.GetString("SCAN_AREA_CLEAR_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Scanning.
        /// </summary>
        public static string SCAN_AREA_CLEAR_1 {
            get {
                return ResourceManager.GetString("SCAN_AREA_CLEAR_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Scanning.
        /// </summary>
        public static string SCAN_AREA_CLEAR_DISABLED {
            get {
                return ResourceManager.GetString("SCAN_AREA_CLEAR_DISABLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prevent Scanning.
        /// </summary>
        public static string SCAN_AREA_CLEAR_ENABLED {
            get {
                return ResourceManager.GetString("SCAN_AREA_CLEAR_ENABLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan Area.
        /// </summary>
        public static string SCAN_AREA_CLEAR_TITLE {
            get {
                return ResourceManager.GetString("SCAN_AREA_CLEAR_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning System Information.
        /// </summary>
        public static string SCAN_COMPLETE_INFO_TITLE {
            get {
                return ResourceManager.GetString("SCAN_COMPLETE_INFO_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configured Settings.
        /// </summary>
        public static string SCAN_CONFIGURATION_TITLE {
            get {
                return ResourceManager.GetString("SCAN_CONFIGURATION_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopped.
        /// </summary>
        public static string SCAN_DRIVE_DIRECTION_0 {
            get {
                return ResourceManager.GetString("SCAN_DRIVE_DIRECTION_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forward.
        /// </summary>
        public static string SCAN_DRIVE_DIRECTION_1 {
            get {
                return ResourceManager.GetString("SCAN_DRIVE_DIRECTION_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reverse.
        /// </summary>
        public static string SCAN_DRIVE_DIRECTION_2 {
            get {
                return ResourceManager.GetString("SCAN_DRIVE_DIRECTION_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direction.
        /// </summary>
        public static string SCAN_DRIVE_DIRECTION_TITLE {
            get {
                return ResourceManager.GetString("SCAN_DRIVE_DIRECTION_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hand brake is enabled.
        /// </summary>
        public static string SCAN_DRIVE_HAND_BRAKE_1 {
            get {
                return ResourceManager.GetString("SCAN_DRIVE_HAND_BRAKE_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        public static string SCAN_DRIVE_HAND_BRAKE_DISABLED {
            get {
                return ResourceManager.GetString("SCAN_DRIVE_HAND_BRAKE_DISABLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string SCAN_DRIVE_HAND_BRAKE_ENABLED {
            get {
                return ResourceManager.GetString("SCAN_DRIVE_HAND_BRAKE_ENABLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hand Brake.
        /// </summary>
        public static string SCAN_DRIVE_HAND_BRAKE_TITLE {
            get {
                return ResourceManager.GetString("SCAN_DRIVE_HAND_BRAKE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %.
        /// </summary>
        public static string SCAN_DRIVE_HYDRAULIC_OIL_LEVEL_MEASUREMENT {
            get {
                return ResourceManager.GetString("SCAN_DRIVE_HYDRAULIC_OIL_LEVEL_MEASUREMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan Drive Oil Level.
        /// </summary>
        public static string SCAN_DRIVE_HYDRAULIC_OIL_LEVEL_TITLE {
            get {
                return ResourceManager.GetString("SCAN_DRIVE_HYDRAULIC_OIL_LEVEL_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to °C.
        /// </summary>
        public static string SCAN_DRIVE_HYDRAULIC_OIL_TEMPERATURE_MEASUREMENT {
            get {
                return ResourceManager.GetString("SCAN_DRIVE_HYDRAULIC_OIL_TEMPERATURE_MEASUREMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan Drive Temperature.
        /// </summary>
        public static string SCAN_DRIVE_HYDRAULIC_OIL_TEMPERATURE_TITLE {
            get {
                return ResourceManager.GetString("SCAN_DRIVE_HYDRAULIC_OIL_TEMPERATURE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The scan drive system is in a powered off state.
        /// </summary>
        public static string SCAN_DRIVE_POWER_STATUS_0 {
            get {
                return ResourceManager.GetString("SCAN_DRIVE_POWER_STATUS_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  m/s.
        /// </summary>
        public static string SCAN_DRIVE_REALTIME_SPEED_MEASUREMENT {
            get {
                return ResourceManager.GetString("SCAN_DRIVE_REALTIME_SPEED_MEASUREMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual Speed.
        /// </summary>
        public static string SCAN_DRIVE_REALTIME_SPEED_TITLE {
            get {
                return ResourceManager.GetString("SCAN_DRIVE_REALTIME_SPEED_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Speed.
        /// </summary>
        public static string SCAN_DRIVE_SELECTED_SPEED_0 {
            get {
                return ResourceManager.GetString("SCAN_DRIVE_SELECTED_SPEED_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low Scan Speed.
        /// </summary>
        public static string SCAN_DRIVE_SELECTED_SPEED_1 {
            get {
                return ResourceManager.GetString("SCAN_DRIVE_SELECTED_SPEED_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium Scan Speed.
        /// </summary>
        public static string SCAN_DRIVE_SELECTED_SPEED_2 {
            get {
                return ResourceManager.GetString("SCAN_DRIVE_SELECTED_SPEED_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Scan Speed.
        /// </summary>
        public static string SCAN_DRIVE_SELECTED_SPEED_3 {
            get {
                return ResourceManager.GetString("SCAN_DRIVE_SELECTED_SPEED_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Speed.
        /// </summary>
        public static string SCAN_DRIVE_SELECTED_SPEED_TITLE {
            get {
                return ResourceManager.GetString("SCAN_DRIVE_SELECTED_SPEED_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The scan drive has become unresponsive..
        /// </summary>
        public static string SCAN_DRIVE_SIGN_OF_LIFE_0 {
            get {
                return ResourceManager.GetString("SCAN_DRIVE_SIGN_OF_LIFE_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The scan drive is unable to achieve the minimal speed threshold for the selected scan speed..
        /// </summary>
        public static string SCAN_DRIVE_SPEED_FAILURE_1 {
            get {
                return ResourceManager.GetString("SCAN_DRIVE_SPEED_FAILURE_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The scan drive is unable to remain below the maximum speed threshold for the selected scan speed..
        /// </summary>
        public static string SCAN_DRIVE_SPEED_FAILURE_2 {
            get {
                return ResourceManager.GetString("SCAN_DRIVE_SPEED_FAILURE_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopped.
        /// </summary>
        public static string SCAN_DRIVE_STATE_0 {
            get {
                return ResourceManager.GetString("SCAN_DRIVE_STATE_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accelerating.
        /// </summary>
        public static string SCAN_DRIVE_STATE_1 {
            get {
                return ResourceManager.GetString("SCAN_DRIVE_STATE_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decelerating.
        /// </summary>
        public static string SCAN_DRIVE_STATE_2 {
            get {
                return ResourceManager.GetString("SCAN_DRIVE_STATE_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running.
        /// </summary>
        public static string SCAN_DRIVE_STATE_3 {
            get {
                return ResourceManager.GetString("SCAN_DRIVE_STATE_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan Step.
        /// </summary>
        public static string SCAN_DRIVE_STATUS_TITLE {
            get {
                return ResourceManager.GetString("SCAN_DRIVE_STATUS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan Drive Subsystem.
        /// </summary>
        public static string SCAN_DRIVE_TITLE {
            get {
                return ResourceManager.GetString("SCAN_DRIVE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single Scan.
        /// </summary>
        public static string SCAN_MULTIPLE_OBJECTS_0 {
            get {
                return ResourceManager.GetString("SCAN_MULTIPLE_OBJECTS_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiscan.
        /// </summary>
        public static string SCAN_MULTIPLE_OBJECTS_1 {
            get {
                return ResourceManager.GetString("SCAN_MULTIPLE_OBJECTS_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set to Multiscan.
        /// </summary>
        public static string SCAN_MULTIPLE_OBJECTS_DISABLED {
            get {
                return ResourceManager.GetString("SCAN_MULTIPLE_OBJECTS_DISABLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set to Single Scan.
        /// </summary>
        public static string SCAN_MULTIPLE_OBJECTS_ENABLED {
            get {
                return ResourceManager.GetString("SCAN_MULTIPLE_OBJECTS_ENABLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning Mode.
        /// </summary>
        public static string SCAN_MULTIPLE_OBJECTS_TITLE {
            get {
                return ResourceManager.GetString("SCAN_MULTIPLE_OBJECTS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan Settings.
        /// </summary>
        public static string SCAN_SETTINGS_TITLE {
            get {
                return ResourceManager.GetString("SCAN_SETTINGS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready to perform scan.
        /// </summary>
        public static string SCAN_STATE_0 {
            get {
                return ResourceManager.GetString("SCAN_STATE_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not ready to perform scan.
        /// </summary>
        public static string SCAN_STATE_1 {
            get {
                return ResourceManager.GetString("SCAN_STATE_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently running scan.
        /// </summary>
        public static string SCAN_STATE_2 {
            get {
                return ResourceManager.GetString("SCAN_STATE_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current State.
        /// </summary>
        public static string SCAN_STATE_TITLE {
            get {
                return ResourceManager.GetString("SCAN_STATE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning Status.
        /// </summary>
        public static string SCAN_STATUS_TITLE {
            get {
                return ResourceManager.GetString("SCAN_STATUS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Scan Step.
        /// </summary>
        public static string SCAN_STEP_LAST_TITLE {
            get {
                return ResourceManager.GetString("SCAN_STEP_LAST_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan Step.
        /// </summary>
        public static string SCAN_STEP_TITLE {
            get {
                return ResourceManager.GetString("SCAN_STEP_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan Status.
        /// </summary>
        public static string STATUSBAR_TITLE {
            get {
                return ResourceManager.GetString("STATUSBAR_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNKNOWN ERROR.
        /// </summary>
        public static string UNKNOWN_RESOURCE {
            get {
                return ResourceManager.GetString("UNKNOWN_RESOURCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan System Warnings.
        /// </summary>
        public static string WARNING_MESSAGES_TITLE {
            get {
                return ResourceManager.GetString("WARNING_MESSAGES_TITLE", resourceCulture);
            }
        }
    }
}
