//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

//
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
//
namespace L3.Cargo.OCR.Messages.ocr_uld {
    using System.Xml.Serialization;


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class message {

        private messageAddressInfo addressInfoField;

        private messageBody bodyField;

        private string nameField;

        private System.DateTime sentDateTimeField;

        /// <remarks/>
        public messageAddressInfo addressInfo {
            get {
                return this.addressInfoField;
            }
            set {
                this.addressInfoField = value;
            }
        }

        /// <remarks/>
        public messageBody body {
            get {
                return this.bodyField;
            }
            set {
                this.bodyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime sentDateTime {
            get {
                return this.sentDateTimeField;
            }
            set {
                this.sentDateTimeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class messageAddressInfo {

        private messageAddressInfoSender senderField;

        /// <remarks/>
        public messageAddressInfoSender sender {
            get {
                return this.senderField;
            }
            set {
                this.senderField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class messageAddressInfoSender {

        private string nameField;

        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class messageBody {

        private messageBodyPayload payloadField;

        private string guidField;

        private bool ackRequiredField;

        private string messageTypeField;

        /// <remarks/>
        public messageBodyPayload payload {
            get {
                return this.payloadField;
            }
            set {
                this.payloadField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string guid {
            get {
                return this.guidField;
            }
            set {
                this.guidField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool ackRequired {
            get {
                return this.ackRequiredField;
            }
            set {
                this.ackRequiredField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string messageType {
            get {
                return this.messageTypeField;
            }
            set {
                this.messageTypeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class messageBodyPayload {

        private ushort eventIDField;

        private byte laneIDField;

        private byte eventTypeField;

        private string eventTimeField;

        private messageBodyPayloadULD uLDField;

        private bool base64EncodedField;

        /// <remarks/>
        public ushort EventID {
            get {
                return this.eventIDField;
            }
            set {
                this.eventIDField = value;
            }
        }

        /// <remarks/>
        public byte LaneID {
            get {
                return this.laneIDField;
            }
            set {
                this.laneIDField = value;
            }
        }

        /// <remarks/>
        public byte EventType {
            get {
                return this.eventTypeField;
            }
            set {
                this.eventTypeField = value;
            }
        }

        /// <remarks/>
        public string EventTime {
            get {
                return this.eventTimeField;
            }
            set {
                this.eventTimeField = value;
            }
        }

        /// <remarks/>
        public messageBodyPayloadULD ULD {
            get {
                return this.uLDField;
            }
            set {
                this.uLDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool base64Encoded {
            get {
                return this.base64EncodedField;
            }
            set {
                this.base64EncodedField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class messageBodyPayloadULD {

        private ulong caseNumberField;

        private string codeField;

        private byte confidenceField;

        private byte resultCodeField;

        private string resultTextField;

        private string fileNameField;

        private byte imageCountField;

        private string image1Field;

        private string image2Field;

        private string image3Field;

        private string image4Field;

        private string image5Field;

        private string image6Field;

        private string image7Field;

        private string image8Field;

        private byte idField;

        /// <remarks/>
        public ulong CaseNumber {
            get {
                return this.caseNumberField;
            }
            set {
                this.caseNumberField = value;
            }
        }

        /// <remarks/>
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }

        /// <remarks/>
        public byte Confidence {
            get {
                return this.confidenceField;
            }
            set {
                this.confidenceField = value;
            }
        }

        /// <remarks/>
        public byte ResultCode {
            get {
                return this.resultCodeField;
            }
            set {
                this.resultCodeField = value;
            }
        }

        /// <remarks/>
        public string ResultText {
            get {
                return this.resultTextField;
            }
            set {
                this.resultTextField = value;
            }
        }

        /// <remarks/>
        public string FileName {
            get {
                return this.fileNameField;
            }
            set {
                this.fileNameField = value;
            }
        }

        /// <remarks/>
        public byte ImageCount {
            get {
                return this.imageCountField;
            }
            set {
                this.imageCountField = value;
            }
        }

        /// <remarks/>
        public string Image1 {
            get {
                return this.image1Field;
            }
            set {
                this.image1Field = value;
            }
        }

        /// <remarks/>
        public string Image2 {
            get {
                return this.image2Field;
            }
            set {
                this.image2Field = value;
            }
        }

        /// <remarks/>
        public string Image3 {
            get {
                return this.image3Field;
            }
            set {
                this.image3Field = value;
            }
        }

        /// <remarks/>
        public string Image4 {
            get {
                return this.image4Field;
            }
            set {
                this.image4Field = value;
            }
        }

        /// <remarks/>
        public string Image5 {
            get {
                return this.image5Field;
            }
            set {
                this.image5Field = value;
            }
        }

        /// <remarks/>
        public string Image6 {
            get {
                return this.image6Field;
            }
            set {
                this.image6Field = value;
            }
        }

        /// <remarks/>
        public string Image7 {
            get {
                return this.image7Field;
            }
            set {
                this.image7Field = value;
            }
        }

        /// <remarks/>
        public string Image8 {
            get {
                return this.image8Field;
            }
            set {
                this.image8Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
}
