//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace L3.Cargo.Common.Dashboard {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("L3.Cargo.Common.Dashboard.Cultures.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build Date:.
        /// </summary>
        public static string BUILDDATE_COLON {
            get {
                return ResourceManager.GetString("BUILDDATE_COLON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build Number:.
        /// </summary>
        public static string BUILDNUMBER_COLON {
            get {
                return ResourceManager.GetString("BUILDNUMBER_COLON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error #.
        /// </summary>
        public static string ERROR_HASH {
            get {
                return ResourceManager.GetString("ERROR_HASH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string LabelCultureName {
            get {
                return ResourceManager.GetString("LabelCultureName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string LANGUAGE {
            get {
                return ResourceManager.GetString("LANGUAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to log out of the ClearView Dashboard.
        /// </summary>
        public static string LOG_OFF_DESCRIPTION {
            get {
                return ResourceManager.GetString("LOG_OFF_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Off System.
        /// </summary>
        public static string LOG_OFF_TITLE {
            get {
                return ResourceManager.GetString("LOG_OFF_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application not connected.
        /// </summary>
        public static string NOT_CONNECTED {
            get {
                return ResourceManager.GetString("NOT_CONNECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critical Errors.
        /// </summary>
        public static string STATUS_ERROR_HEADER {
            get {
                return ResourceManager.GetString("STATUS_ERROR_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are currently no System Errors.
        /// </summary>
        public static string STATUS_NO_ERRORS_MESSAGE {
            get {
                return ResourceManager.GetString("STATUS_NO_ERRORS_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are currently no System Warnings.
        /// </summary>
        public static string STATUS_NO_WARNINGS_MESSAGE {
            get {
                return ResourceManager.GetString("STATUS_NO_WARNINGS_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning Messages.
        /// </summary>
        public static string STATUS_WARNING_HEADER {
            get {
                return ResourceManager.GetString("STATUS_WARNING_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:.
        /// </summary>
        public static string VERSION_COLON {
            get {
                return ResourceManager.GetString("VERSION_COLON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning #.
        /// </summary>
        public static string WARNING_HASH {
            get {
                return ResourceManager.GetString("WARNING_HASH", resourceCulture);
            }
        }
    }
}
