//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace L3.Cargo.Safety.Display.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("L3.Cargo.Safety.Display.Common.Cultures.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barcode Sensor Status.
        /// </summary>
        public static string BARCODE_READ {
            get {
                return ResourceManager.GetString("BARCODE_READ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barcode Read Status.
        /// </summary>
        public static string BARCODE_READ_TITLE {
            get {
                return ResourceManager.GetString("BARCODE_READ_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barcode is Good.
        /// </summary>
        public static string BARCODE_STATE_0 {
            get {
                return ResourceManager.GetString("BARCODE_STATE_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barcode is Bad.
        /// </summary>
        public static string BARCODE_STATE_1 {
            get {
                return ResourceManager.GetString("BARCODE_STATE_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Safety Subsystem Information.
        /// </summary>
        public static string COMPLETE_INFO_TITLE {
            get {
                return ResourceManager.GetString("COMPLETE_INFO_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doppler Radar Sensor Speed.
        /// </summary>
        public static string DOPPLER_RADAR_SENSOR_LEFT {
            get {
                return ResourceManager.GetString("DOPPLER_RADAR_SENSOR_LEFT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doppler Radar Sensor Speed (Exit Left).
        /// </summary>
        public static string DOPPLER_RADAR_SENSOR_LEFT_TITLE {
            get {
                return ResourceManager.GetString("DOPPLER_RADAR_SENSOR_LEFT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doppler Radar Sensor Speed.
        /// </summary>
        public static string DOPPLER_RADAR_SENSOR_RIGHT {
            get {
                return ResourceManager.GetString("DOPPLER_RADAR_SENSOR_RIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doppler Radar Sensor Speed (Exit Right).
        /// </summary>
        public static string DOPPLER_RADAR_SENSOR_RIGHT_TITLE {
            get {
                return ResourceManager.GetString("DOPPLER_RADAR_SENSOR_RIGHT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Safety System Errors.
        /// </summary>
        public static string ERROR_MESSAGES_TITLE {
            get {
                return ResourceManager.GetString("ERROR_MESSAGES_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator&apos;s console E-Stop is pressed and needs to be manually reset..
        /// </summary>
        public static string ESTOP_OPERATORS_CONSOLE_1 {
            get {
                return ResourceManager.GetString("ESTOP_OPERATORS_CONSOLE_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator&apos;s console E-Stop was reset, now waiting for operator to press &quot;Clear Safety Faults&quot; button..
        /// </summary>
        public static string ESTOP_OPERATORS_CONSOLE_2 {
            get {
                return ResourceManager.GetString("ESTOP_OPERATORS_CONSOLE_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator&apos;s Console (ES1).
        /// </summary>
        public static string ESTOP_OPERATORS_CONSOLE_TITLE {
            get {
                return ResourceManager.GetString("ESTOP_OPERATORS_CONSOLE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string ESTOP_STATE_0 {
            get {
                return ResourceManager.GetString("ESTOP_STATE_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engaged.
        /// </summary>
        public static string ESTOP_STATE_1 {
            get {
                return ResourceManager.GetString("ESTOP_STATE_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Needs to be Cleared.
        /// </summary>
        public static string ESTOP_STATE_2 {
            get {
                return ResourceManager.GetString("ESTOP_STATE_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Stops.
        /// </summary>
        public static string ESTOP_STATUS_TITLE {
            get {
                return ResourceManager.GetString("ESTOP_STATUS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tunnel entry left E-Stop rope is pulled and needs to be manually reset..
        /// </summary>
        public static string ESTOP_TUNNEL_ENTRY_LEFT_1 {
            get {
                return ResourceManager.GetString("ESTOP_TUNNEL_ENTRY_LEFT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tunnel entry left E-Stop was reset, now waiting for operator to press &quot;Clear Safety Faults&quot; button..
        /// </summary>
        public static string ESTOP_TUNNEL_ENTRY_LEFT_2 {
            get {
                return ResourceManager.GetString("ESTOP_TUNNEL_ENTRY_LEFT_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tunnel Entry Left (ES4).
        /// </summary>
        public static string ESTOP_TUNNEL_ENTRY_LEFT_TITLE {
            get {
                return ResourceManager.GetString("ESTOP_TUNNEL_ENTRY_LEFT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tunnel entry right E-Stop rope is pulled and needs to be manually reset..
        /// </summary>
        public static string ESTOP_TUNNEL_ENTRY_RIGHT_1 {
            get {
                return ResourceManager.GetString("ESTOP_TUNNEL_ENTRY_RIGHT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tunnel entry right E-Stop was reset, now waiting for operator to press &quot;Clear Safety Faults&quot; button..
        /// </summary>
        public static string ESTOP_TUNNEL_ENTRY_RIGHT_2 {
            get {
                return ResourceManager.GetString("ESTOP_TUNNEL_ENTRY_RIGHT_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tunnel Entry Right (ES3).
        /// </summary>
        public static string ESTOP_TUNNEL_ENTRY_RIGHT_TITLE {
            get {
                return ResourceManager.GetString("ESTOP_TUNNEL_ENTRY_RIGHT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tunnel exit left E-Stop is pulled and needs to be manually reset..
        /// </summary>
        public static string ESTOP_TUNNEL_EXIT_LEFT_1 {
            get {
                return ResourceManager.GetString("ESTOP_TUNNEL_EXIT_LEFT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tunnel exit left E-Stop was reset, now waiting for operator to press &quot;Clear Safety Faults&quot; button..
        /// </summary>
        public static string ESTOP_TUNNEL_EXIT_LEFT_2 {
            get {
                return ResourceManager.GetString("ESTOP_TUNNEL_EXIT_LEFT_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tunnel Exit Left (ES6).
        /// </summary>
        public static string ESTOP_TUNNEL_EXIT_LEFT_TITLE {
            get {
                return ResourceManager.GetString("ESTOP_TUNNEL_EXIT_LEFT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tunnel exit right E-Stop rope is pulled and needs to be manually reset..
        /// </summary>
        public static string ESTOP_TUNNEL_EXIT_RIGHT_1 {
            get {
                return ResourceManager.GetString("ESTOP_TUNNEL_EXIT_RIGHT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tunnel exit right E-Stop was reset, now waiting for operator to press &quot;Clear Safety Faults&quot; button..
        /// </summary>
        public static string ESTOP_TUNNEL_EXIT_RIGHT_2 {
            get {
                return ResourceManager.GetString("ESTOP_TUNNEL_EXIT_RIGHT_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tunnel Exit Right (ES5).
        /// </summary>
        public static string ESTOP_TUNNEL_EXIT_RIGHT_TITLE {
            get {
                return ResourceManager.GetString("ESTOP_TUNNEL_EXIT_RIGHT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical detector box E-Stop is pressed and needs to be manually reset..
        /// </summary>
        public static string ESTOP_VERT_DETECTOR_BOX_1 {
            get {
                return ResourceManager.GetString("ESTOP_VERT_DETECTOR_BOX_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical detector box E-Stop was reset, now waiting for operator to press &quot;Clear Safety Faults&quot; button..
        /// </summary>
        public static string ESTOP_VERT_DETECTOR_BOX_2 {
            get {
                return ResourceManager.GetString("ESTOP_VERT_DETECTOR_BOX_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical Detector Box (ES7).
        /// </summary>
        public static string ESTOP_VERT_DETECTOR_BOX_TITLE {
            get {
                return ResourceManager.GetString("ESTOP_VERT_DETECTOR_BOX_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X-ray source area E-Stop is pressed and needs to be manually reset..
        /// </summary>
        public static string ESTOP_XRAY_SOURCE_AREA_1 {
            get {
                return ResourceManager.GetString("ESTOP_XRAY_SOURCE_AREA_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X-ray source area E-Stop was reset, now waiting for operator to press &quot;Clear Safety Faults&quot; button..
        /// </summary>
        public static string ESTOP_XRAY_SOURCE_AREA_2 {
            get {
                return ResourceManager.GetString("ESTOP_XRAY_SOURCE_AREA_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X-ray Source Area (ES2).
        /// </summary>
        public static string ESTOP_XRAY_SOURCE_AREA_TITLE {
            get {
                return ResourceManager.GetString("ESTOP_XRAY_SOURCE_AREA_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string IN_MDS_VEHICLE_MOTION_DET_SAFETY_STATE_0 {
            get {
                return ResourceManager.GetString("IN_MDS_VEHICLE_MOTION_DET_SAFETY_STATE_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Detected.
        /// </summary>
        public static string IN_MDS_VEHICLE_MOTION_DET_SAFETY_STATE_1 {
            get {
                return ResourceManager.GetString("IN_MDS_VEHICLE_MOTION_DET_SAFETY_STATE_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle was detected by motion detector #3, but the &quot;Clear Safety Faults&quot; button must be pressed before a scan can be performed..
        /// </summary>
        public static string IN_MDS3_VEHICLE_MOTION_DET_1 {
            get {
                return ResourceManager.GetString("IN_MDS3_VEHICLE_MOTION_DET_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Motion Detector #3 (MDS3-P).
        /// </summary>
        public static string IN_MDS3_VEHICLE_MOTION_DET_TITLE {
            get {
                return ResourceManager.GetString("IN_MDS3_VEHICLE_MOTION_DET_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle detected by motion detector #4.  A scan cannot be performed until the area is clear..
        /// </summary>
        public static string IN_MDS4_VEHICLE_MOTION_DET_1 {
            get {
                return ResourceManager.GetString("IN_MDS4_VEHICLE_MOTION_DET_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Motion Detector #4  (MDS4-P).
        /// </summary>
        public static string IN_MDS4_VEHICLE_MOTION_DET_TITLE {
            get {
                return ResourceManager.GetString("IN_MDS4_VEHICLE_MOTION_DET_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display all information about the Safety system..
        /// </summary>
        public static string INFO_BUTTON_DESCRIPTION {
            get {
                return ResourceManager.GetString("INFO_BUTTON_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Safety System.
        /// </summary>
        public static string INFO_BUTTON_TITLE {
            get {
                return ResourceManager.GetString("INFO_BUTTON_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable interlock checks.
        /// </summary>
        public static string INTERLOCK_BYPASS_DISABLE {
            get {
                return ResourceManager.GetString("INTERLOCK_BYPASS_DISABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable interlock checks.
        /// </summary>
        public static string INTERLOCK_BYPASS_ENABLE {
            get {
                return ResourceManager.GetString("INTERLOCK_BYPASS_ENABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interlock Bypass.
        /// </summary>
        public static string INTERLOCK_BYPASS_TITLE {
            get {
                return ResourceManager.GetString("INTERLOCK_BYPASS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LINAC room door is open.  A scan cannot be performed until the door has been closed..
        /// </summary>
        public static string INTERLOCK_DOOR_0 {
            get {
                return ResourceManager.GetString("INTERLOCK_DOOR_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LINAC room door has been closed, but the &quot;Clear Safety Faults&quot; button must be pressed before a scan can be performed..
        /// </summary>
        public static string INTERLOCK_DOOR_2 {
            get {
                return ResourceManager.GetString("INTERLOCK_DOOR_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LINAC Room Door.
        /// </summary>
        public static string INTERLOCK_DOOR_TITLE {
            get {
                return ResourceManager.GetString("INTERLOCK_DOOR_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X-ray enable keyswitch is off.  A scan cannot be performed until the X-ray enable keyswitch is on..
        /// </summary>
        public static string INTERLOCK_KSW_XRAY_ENABLE_0 {
            get {
                return ResourceManager.GetString("INTERLOCK_KSW_XRAY_ENABLE_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X-ray enable keyswitch is now on, but the &quot;Clear Safety Faults&quot; button must be pressed before a scan can be performed..
        /// </summary>
        public static string INTERLOCK_KSW_XRAY_ENABLE_2 {
            get {
                return ResourceManager.GetString("INTERLOCK_KSW_XRAY_ENABLE_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X-ray Enable Keyswitch (KSW1).
        /// </summary>
        public static string INTERLOCK_KSW_XRAY_ENABLE_TITLE {
            get {
                return ResourceManager.GetString("INTERLOCK_KSW_XRAY_ENABLE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Curtain blocked.
        /// </summary>
        public static string INTERLOCK_LC_SAFETY_STATE_0 {
            get {
                return ResourceManager.GetString("INTERLOCK_LC_SAFETY_STATE_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string INTERLOCK_LC_SAFETY_STATE_1 {
            get {
                return ResourceManager.GetString("INTERLOCK_LC_SAFETY_STATE_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Needs to be Cleared.
        /// </summary>
        public static string INTERLOCK_LC_SAFETY_STATE_2 {
            get {
                return ResourceManager.GetString("INTERLOCK_LC_SAFETY_STATE_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personnel safety light curtain #1 is blocked.  A scan cannot be performed until the area is clear..
        /// </summary>
        public static string INTERLOCK_LC1_0 {
            get {
                return ResourceManager.GetString("INTERLOCK_LC1_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personnel safety light curtain #1 is unblocked..
        /// </summary>
        public static string INTERLOCK_LC1_1 {
            get {
                return ResourceManager.GetString("INTERLOCK_LC1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personnel safety light curtain #1 was blocked, but the &quot;Clear Safety Faults&quot; button must be pressed before a scan can be performed..
        /// </summary>
        public static string INTERLOCK_LC1_2 {
            get {
                return ResourceManager.GetString("INTERLOCK_LC1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personnel Safety Light Curtain #1 (LC1 OSSD1).
        /// </summary>
        public static string INTERLOCK_LC1_TITLE {
            get {
                return ResourceManager.GetString("INTERLOCK_LC1_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personnel safety light curtain #1 is blocked.  A scan cannot be performed until the area is clear..
        /// </summary>
        public static string INTERLOCK_LC2_0 {
            get {
                return ResourceManager.GetString("INTERLOCK_LC2_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personnel safety light curtain is unblocked..
        /// </summary>
        public static string INTERLOCK_LC2_1 {
            get {
                return ResourceManager.GetString("INTERLOCK_LC2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personnel safety light curtain #2 was blocked, but the &quot;Clear Safety Faults&quot; button must be pressed before a scan can be performed..
        /// </summary>
        public static string INTERLOCK_LC2_2 {
            get {
                return ResourceManager.GetString("INTERLOCK_LC2_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personnel Safety Light Curtain #2 (LC2 OSSD2).
        /// </summary>
        public static string INTERLOCK_LC2_TITLE {
            get {
                return ResourceManager.GetString("INTERLOCK_LC2_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person detected by motion detector #1.  A scan cannot be performed until the area is clear..
        /// </summary>
        public static string INTERLOCK_MDS_PERSONNEL_SAFETY_1_1 {
            get {
                return ResourceManager.GetString("INTERLOCK_MDS_PERSONNEL_SAFETY_1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person was detected by motion detector #1, but the &quot;Clear Safety Faults&quot; button must be pressed before a scan can be performed..
        /// </summary>
        public static string INTERLOCK_MDS_PERSONNEL_SAFETY_1_2 {
            get {
                return ResourceManager.GetString("INTERLOCK_MDS_PERSONNEL_SAFETY_1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personnel Motion Detector #1 (MDS1-P).
        /// </summary>
        public static string INTERLOCK_MDS_PERSONNEL_SAFETY_1_TITLE {
            get {
                return ResourceManager.GetString("INTERLOCK_MDS_PERSONNEL_SAFETY_1_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person detected by motion detector #2.  A scan cannot be performed until the area is clear..
        /// </summary>
        public static string INTERLOCK_MDS_PERSONNEL_SAFETY_2_1 {
            get {
                return ResourceManager.GetString("INTERLOCK_MDS_PERSONNEL_SAFETY_2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person was detected by motion detector #2, but the &quot;Clear Safety Faults&quot; button must be pressed before a scan can be performed..
        /// </summary>
        public static string INTERLOCK_MDS_PERSONNEL_SAFETY_2_2 {
            get {
                return ResourceManager.GetString("INTERLOCK_MDS_PERSONNEL_SAFETY_2_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personnel Motion Detector #2 (MDS2-P).
        /// </summary>
        public static string INTERLOCK_MDS_PERSONNEL_SAFETY_2_TITLE {
            get {
                return ResourceManager.GetString("INTERLOCK_MDS_PERSONNEL_SAFETY_2_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string INTERLOCK_MDS_PERSONNEL_SAFETY_STATE_0 {
            get {
                return ResourceManager.GetString("INTERLOCK_MDS_PERSONNEL_SAFETY_STATE_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presence of personnel detected.
        /// </summary>
        public static string INTERLOCK_MDS_PERSONNEL_SAFETY_STATE_1 {
            get {
                return ResourceManager.GetString("INTERLOCK_MDS_PERSONNEL_SAFETY_STATE_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Needs to be Cleared.
        /// </summary>
        public static string INTERLOCK_MDS_PERSONNEL_SAFETY_STATE_2 {
            get {
                return ResourceManager.GetString("INTERLOCK_MDS_PERSONNEL_SAFETY_STATE_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed.
        /// </summary>
        public static string INTERLOCK_STATE_0 {
            get {
                return ResourceManager.GetString("INTERLOCK_STATE_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string INTERLOCK_STATE_1 {
            get {
                return ResourceManager.GetString("INTERLOCK_STATE_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Needs to be Cleared.
        /// </summary>
        public static string INTERLOCK_STATE_2 {
            get {
                return ResourceManager.GetString("INTERLOCK_STATE_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interlocks.
        /// </summary>
        public static string INTERLOCK_STATE_TITLE {
            get {
                return ResourceManager.GetString("INTERLOCK_STATE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interlock bypass disabled.
        /// </summary>
        public static string KSW_INTERLOCK_BYPASS_0 {
            get {
                return ResourceManager.GetString("KSW_INTERLOCK_BYPASS_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interlock bypass enabled.
        /// </summary>
        public static string KSW_INTERLOCK_BYPASS_1 {
            get {
                return ResourceManager.GetString("KSW_INTERLOCK_BYPASS_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Safety Interlock Bypass Keyswitch (KSW2).
        /// </summary>
        public static string KSW_INTERLOCK_BYPASS_TITLE {
            get {
                return ResourceManager.GetString("KSW_INTERLOCK_BYPASS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string LOCATION {
            get {
                return ResourceManager.GetString("LOCATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perimeter field has detected an intrusion between perimeter posts 1 - 2.
        /// </summary>
        public static string PERIMETER_INTRUSIONS_STATE_1 {
            get {
                return ResourceManager.GetString("PERIMETER_INTRUSIONS_STATE_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perimeter field has detected an intrusion between perimeter posts 3 -4 and 1 - 4.
        /// </summary>
        public static string PERIMETER_INTRUSIONS_STATE_10 {
            get {
                return ResourceManager.GetString("PERIMETER_INTRUSIONS_STATE_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perimeter field has detected an intrusion between perimeter posts 1 - 2 and 2 - 3 and 3 - 4.
        /// </summary>
        public static string PERIMETER_INTRUSIONS_STATE_11 {
            get {
                return ResourceManager.GetString("PERIMETER_INTRUSIONS_STATE_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perimeter field has detected an intrusion between perimeter posts 1 - 2 and 2 - 3 and 1 - 4.
        /// </summary>
        public static string PERIMETER_INTRUSIONS_STATE_12 {
            get {
                return ResourceManager.GetString("PERIMETER_INTRUSIONS_STATE_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perimeter field has detected an intrusion between perimeter posts 1 - 2 and 3 - 4 and 1 - 4.
        /// </summary>
        public static string PERIMETER_INTRUSIONS_STATE_13 {
            get {
                return ResourceManager.GetString("PERIMETER_INTRUSIONS_STATE_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perimeter field has detected an intrusion between perimeter posts 2 - 3 and 3 - 4 and 1 - 4.
        /// </summary>
        public static string PERIMETER_INTRUSIONS_STATE_14 {
            get {
                return ResourceManager.GetString("PERIMETER_INTRUSIONS_STATE_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perimeter field has detected an intrusion between perimeter posts 1 - 2 and 2 - 3 and 3 - 4 and 1 - 4.
        /// </summary>
        public static string PERIMETER_INTRUSIONS_STATE_15 {
            get {
                return ResourceManager.GetString("PERIMETER_INTRUSIONS_STATE_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perimeter field has detected an intrusion between perimeter posts 2 - 3.
        /// </summary>
        public static string PERIMETER_INTRUSIONS_STATE_2 {
            get {
                return ResourceManager.GetString("PERIMETER_INTRUSIONS_STATE_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perimeter field has detected an intrusion between perimeter posts 3 - 4.
        /// </summary>
        public static string PERIMETER_INTRUSIONS_STATE_3 {
            get {
                return ResourceManager.GetString("PERIMETER_INTRUSIONS_STATE_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perimeter field has detected an intrusion between perimeter posts 1 - 4.
        /// </summary>
        public static string PERIMETER_INTRUSIONS_STATE_4 {
            get {
                return ResourceManager.GetString("PERIMETER_INTRUSIONS_STATE_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perimeter field has detected an intrusion between perimeter posts 1 - 2 and 2 - 3.
        /// </summary>
        public static string PERIMETER_INTRUSIONS_STATE_5 {
            get {
                return ResourceManager.GetString("PERIMETER_INTRUSIONS_STATE_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perimeter field has detected an intrusion between perimeter posts 1 - 2 and 3 - 4.
        /// </summary>
        public static string PERIMETER_INTRUSIONS_STATE_6 {
            get {
                return ResourceManager.GetString("PERIMETER_INTRUSIONS_STATE_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perimeter field has detected an intrusion between perimeter posts 1 - 2 and 1 - 4.
        /// </summary>
        public static string PERIMETER_INTRUSIONS_STATE_7 {
            get {
                return ResourceManager.GetString("PERIMETER_INTRUSIONS_STATE_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perimeter field has detected an intrusion between perimeter posts 2 - 3 and 3 - 4.
        /// </summary>
        public static string PERIMETER_INTRUSIONS_STATE_8 {
            get {
                return ResourceManager.GetString("PERIMETER_INTRUSIONS_STATE_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perimeter field has detected an intrusion between perimeter posts 2 - 3 and 1 - 4.
        /// </summary>
        public static string PERIMETER_INTRUSIONS_STATE_9 {
            get {
                return ResourceManager.GetString("PERIMETER_INTRUSIONS_STATE_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Perimeter.
        /// </summary>
        public static string PERIMETER_MODE_0 {
            get {
                return ResourceManager.GetString("PERIMETER_MODE_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Perimeter.
        /// </summary>
        public static string PERIMETER_MODE_1 {
            get {
                return ResourceManager.GetString("PERIMETER_MODE_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perimeter Detection.
        /// </summary>
        public static string PERIMETER_MODE_TITLE {
            get {
                return ResourceManager.GetString("PERIMETER_MODE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cabin radiation has exceeded acceptable limits.  Please press Safety reset button to continue operations..
        /// </summary>
        public static string RADIATION_MONITOR_1 {
            get {
                return ResourceManager.GetString("RADIATION_MONITOR_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cabin Radiation is nearing limits.
        /// </summary>
        public static string RADIATION_MONITOR_2 {
            get {
                return ResourceManager.GetString("RADIATION_MONITOR_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed.
        /// </summary>
        public static string RADIATION_MONITOR_STATE_0 {
            get {
                return ResourceManager.GetString("RADIATION_MONITOR_STATE_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Needs to be Cleared.
        /// </summary>
        public static string RADIATION_MONITOR_STATE_1 {
            get {
                return ResourceManager.GetString("RADIATION_MONITOR_STATE_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed.
        /// </summary>
        public static string RADIATION_MONITOR_STATE_2 {
            get {
                return ResourceManager.GetString("RADIATION_MONITOR_STATE_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radiation Monitor.
        /// </summary>
        public static string RADIATION_MONITOR_TITLE {
            get {
                return ResourceManager.GetString("RADIATION_MONITOR_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Safety Faults.
        /// </summary>
        public static string SAFETY_RESET_FAULTS_BUTTON {
            get {
                return ResourceManager.GetString("SAFETY_RESET_FAULTS_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Safety Faults.
        /// </summary>
        public static string SAFETY_RESET_TITLE {
            get {
                return ResourceManager.GetString("SAFETY_RESET_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Safety Systems.
        /// </summary>
        public static string SAFETY_STATES_TITLE {
            get {
                return ResourceManager.GetString("SAFETY_STATES_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string STATE {
            get {
                return ResourceManager.GetString("STATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Safety Status.
        /// </summary>
        public static string STATUSBAR_TITLE {
            get {
                return ResourceManager.GetString("STATUSBAR_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operational Status.
        /// </summary>
        public static string SUMMARY_STATUS_TITLE {
            get {
                return ResourceManager.GetString("SUMMARY_STATUS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNKNOWN ERROR.
        /// </summary>
        public static string UNKNOWN_RESOURCE {
            get {
                return ResourceManager.GetString("UNKNOWN_RESOURCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Not Present.
        /// </summary>
        public static string VEHICLE_NOT_DETECTED_0 {
            get {
                return ResourceManager.GetString("VEHICLE_NOT_DETECTED_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Present.
        /// </summary>
        public static string VEHICLE_NOT_DETECTED_1 {
            get {
                return ResourceManager.GetString("VEHICLE_NOT_DETECTED_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Sensor Status (After XRay at the Left) no vehicle is present.
        /// </summary>
        public static string VEHICLE_SENSOR_AFTER_XRAY_LEFT_1 {
            get {
                return ResourceManager.GetString("VEHICLE_SENSOR_AFTER_XRAY_LEFT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Sensor Status (After XRay at the Left) detected vehicle.
        /// </summary>
        public static string VEHICLE_SENSOR_AFTER_XRAY_LEFT_2 {
            get {
                return ResourceManager.GetString("VEHICLE_SENSOR_AFTER_XRAY_LEFT_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Sensor Status (After XRay at the Left).
        /// </summary>
        public static string VEHICLE_SENSOR_AFTER_XRAY_LEFT_TITLE {
            get {
                return ResourceManager.GetString("VEHICLE_SENSOR_AFTER_XRAY_LEFT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Sensor Status (After XRay at the Right) no vehicle is present.
        /// </summary>
        public static string VEHICLE_SENSOR_AFTER_XRAY_RIGHT_1 {
            get {
                return ResourceManager.GetString("VEHICLE_SENSOR_AFTER_XRAY_RIGHT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Sensor Status (After XRay at the Right) detected vehicle.
        /// </summary>
        public static string VEHICLE_SENSOR_AFTER_XRAY_RIGHT_2 {
            get {
                return ResourceManager.GetString("VEHICLE_SENSOR_AFTER_XRAY_RIGHT_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Sensor Status (After XRay at the Right).
        /// </summary>
        public static string VEHICLE_SENSOR_AFTER_XRAY_RIGHT_TITLE {
            get {
                return ResourceManager.GetString("VEHICLE_SENSOR_AFTER_XRAY_RIGHT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Sensor Status (At Gate at Left) no vehicle is present.
        /// </summary>
        public static string VEHICLE_SENSOR_AT_GATE_LEFT_1 {
            get {
                return ResourceManager.GetString("VEHICLE_SENSOR_AT_GATE_LEFT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Sensor Status (At Gate at Left) detected vehicle.
        /// </summary>
        public static string VEHICLE_SENSOR_AT_GATE_LEFT_2 {
            get {
                return ResourceManager.GetString("VEHICLE_SENSOR_AT_GATE_LEFT_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Sensor Status (At Gate at Left).
        /// </summary>
        public static string VEHICLE_SENSOR_AT_GATE_LEFT_TITLE {
            get {
                return ResourceManager.GetString("VEHICLE_SENSOR_AT_GATE_LEFT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Sensor Status (At Gate at Right) no vehicle is present.
        /// </summary>
        public static string VEHICLE_SENSOR_AT_GATE_RIGHT_1 {
            get {
                return ResourceManager.GetString("VEHICLE_SENSOR_AT_GATE_RIGHT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Sensor Status (At Gate at Right) detected vehicle.
        /// </summary>
        public static string VEHICLE_SENSOR_AT_GATE_RIGHT_2 {
            get {
                return ResourceManager.GetString("VEHICLE_SENSOR_AT_GATE_RIGHT_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Sensor Status (At Gate at Right).
        /// </summary>
        public static string VEHICLE_SENSOR_AT_GATE_RIGHT_TITLE {
            get {
                return ResourceManager.GetString("VEHICLE_SENSOR_AT_GATE_RIGHT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Sensor Status (Before XRay at the Left) no vehicle is present.
        /// </summary>
        public static string VEHICLE_SENSOR_BEFORE_XRAY_LEFT_1 {
            get {
                return ResourceManager.GetString("VEHICLE_SENSOR_BEFORE_XRAY_LEFT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Sensor Status (Before XRay at the Left) detected vehicle.
        /// </summary>
        public static string VEHICLE_SENSOR_BEFORE_XRAY_LEFT_2 {
            get {
                return ResourceManager.GetString("VEHICLE_SENSOR_BEFORE_XRAY_LEFT_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Sensor Status (Before XRay at the Left).
        /// </summary>
        public static string VEHICLE_SENSOR_BEFORE_XRAY_LEFT_TITLE {
            get {
                return ResourceManager.GetString("VEHICLE_SENSOR_BEFORE_XRAY_LEFT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Sensor Status (Before XRay at the Right) no vehicle is present.
        /// </summary>
        public static string VEHICLE_SENSOR_BEFORE_XRAY_RIGHT_1 {
            get {
                return ResourceManager.GetString("VEHICLE_SENSOR_BEFORE_XRAY_RIGHT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Sensor Status (Before XRay at the Right) detected vehicle.
        /// </summary>
        public static string VEHICLE_SENSOR_BEFORE_XRAY_RIGHT_2 {
            get {
                return ResourceManager.GetString("VEHICLE_SENSOR_BEFORE_XRAY_RIGHT_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Sensor Status (Before XRay at the Right).
        /// </summary>
        public static string VEHICLE_SENSOR_BEFORE_XRAY_RIGHT_TITLE {
            get {
                return ResourceManager.GetString("VEHICLE_SENSOR_BEFORE_XRAY_RIGHT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of Vehicle Detected.
        /// </summary>
        public static string VEHICLE_TYPE {
            get {
                return ResourceManager.GetString("VEHICLE_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Vehicle Detected.
        /// </summary>
        public static string VEHICLE_TYPE_STATE_0 {
            get {
                return ResourceManager.GetString("VEHICLE_TYPE_STATE_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small Vehicle Detected.
        /// </summary>
        public static string VEHICLE_TYPE_STATE_1 {
            get {
                return ResourceManager.GetString("VEHICLE_TYPE_STATE_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium Vehicle Detected.
        /// </summary>
        public static string VEHICLE_TYPE_STATE_2 {
            get {
                return ResourceManager.GetString("VEHICLE_TYPE_STATE_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Large Vehicle Detected.
        /// </summary>
        public static string VEHICLE_TYPE_STATE_3 {
            get {
                return ResourceManager.GetString("VEHICLE_TYPE_STATE_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of Vehicle Detection Sensor.
        /// </summary>
        public static string VEHICLE_TYPE_TITLE {
            get {
                return ResourceManager.GetString("VEHICLE_TYPE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Safety System Warnings.
        /// </summary>
        public static string WARNING_MESSAGES_TITLE {
            get {
                return ResourceManager.GetString("WARNING_MESSAGES_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string WARNING_STATE_0 {
            get {
                return ResourceManager.GetString("WARNING_STATE_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string WARNING_STATE_1 {
            get {
                return ResourceManager.GetString("WARNING_STATE_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to turn on.
        /// </summary>
        public static string WARNING_STATE_2 {
            get {
                return ResourceManager.GetString("WARNING_STATE_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning System.
        /// </summary>
        public static string WARNING_STATE_TITLE {
            get {
                return ResourceManager.GetString("WARNING_STATE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning System.
        /// </summary>
        public static string WARNING_STATUS_TITLE {
            get {
                return ResourceManager.GetString("WARNING_STATUS_TITLE", resourceCulture);
            }
        }
    }
}
