//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Windows;
using System.Windows.Media;
using System.Windows.Media.Effects;


namespace L3.Cargo.Workstation.Plugins.XRayImageBase
{

	public class ColorMappingEffect : ShaderEffect {
		public static readonly DependencyProperty InputProperty = ShaderEffect.RegisterPixelShaderSamplerProperty("Input", typeof(ColorMappingEffect), 0);
		public static readonly DependencyProperty MappingTextureSamplerProperty = ShaderEffect.RegisterPixelShaderSamplerProperty("MappingTextureSampler", typeof(ColorMappingEffect), 1);
		public ColorMappingEffect() {
			PixelShader pixelShader = new PixelShader();
			pixelShader.UriSource = new Uri(@"/L3.Cargo.Workstation.Plugins.XRayImageBase;component/Effects/ColorMapping.ps", UriKind.Relative);
			this.PixelShader = pixelShader;

			this.UpdateShaderValue(InputProperty);
			this.UpdateShaderValue(MappingTextureSamplerProperty);
		}
		public Brush Input {
			get {
				return ((Brush)(this.GetValue(InputProperty)));
			}
			set {
				this.SetValue(InputProperty, value);
			}
		}
		public Brush MappingTextureSampler {
			get {
				return ((Brush)(this.GetValue(MappingTextureSamplerProperty)));
			}
			set {
				this.SetValue(MappingTextureSamplerProperty, value);
			}
		}
	}
}
