//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace L3.Cargo.Linac.Display.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("L3.Cargo.Linac.Display.Common.Cultures.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accelerator coolant flow is faulted..
        /// </summary>
        public static string ACCELERATOR_FLOW_STATUS_1 {
            get {
                return ResourceManager.GetString("ACCELERATOR_FLOW_STATUS_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linac has encountered excessive pressure in accelerator..
        /// </summary>
        public static string ACCELERATOR_VACUUM_STATUS_1 {
            get {
                return ResourceManager.GetString("ACCELERATOR_VACUUM_STATUS_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AFC Process Variable.
        /// </summary>
        public static string AFC_PV_TITLE {
            get {
                return ResourceManager.GetString("AFC_PV_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stepper Motor is out of position..
        /// </summary>
        public static string AFC_STEPPER_MOTOR_OUT_OF_BOUND_STATUS_1 {
            get {
                return ResourceManager.GetString("AFC_STEPPER_MOTOR_OUT_OF_BOUND_STATUS_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linac System Information.
        /// </summary>
        public static string COMPLETE_INFO_TITLE {
            get {
                return ResourceManager.GetString("COMPLETE_INFO_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linac accelerator temperature is above acceptable limits..
        /// </summary>
        public static string COOLANT_TEMPERATURE_STATUS_1 {
            get {
                return ResourceManager.GetString("COOLANT_TEMPERATURE_STATUS_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A.
        /// </summary>
        public static string CURRENT_MEASUREMENT {
            get {
                return ResourceManager.GetString("CURRENT_MEASUREMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linac has encountered an external interlock. (CI1).
        /// </summary>
        public static string CUSTOMER_INTERLOCK1_STATUS_1 {
            get {
                return ResourceManager.GetString("CUSTOMER_INTERLOCK1_STATUS_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linac has encountered an external interlock. (CI2).
        /// </summary>
        public static string CUSTOMER_INTERLOCK2_STATUS_1 {
            get {
                return ResourceManager.GetString("CUSTOMER_INTERLOCK2_STATUS_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enclosure panels are open.  Please close panels before continuing operations..
        /// </summary>
        public static string ENCLOSURE_PANELS_STATUS_1 {
            get {
                return ResourceManager.GetString("ENCLOSURE_PANELS_STATUS_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linac enclosure temperature is above acceptable limits..
        /// </summary>
        public static string ENCLOSURE_TEMPERATURE_STATUS_1 {
            get {
                return ResourceManager.GetString("ENCLOSURE_TEMPERATURE_STATUS_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linac System Errors.
        /// </summary>
        public static string ERROR_MESSAGES_TITLE {
            get {
                return ResourceManager.GetString("ERROR_MESSAGES_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RF Forward Power.
        /// </summary>
        public static string FORWARD_POWER_TITLE {
            get {
                return ResourceManager.GetString("FORWARD_POWER_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gun Driver Beam Current.
        /// </summary>
        public static string GD_BEAM_CURRENT_TITLE {
            get {
                return ResourceManager.GetString("GD_BEAM_CURRENT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gun Driver Cathode Voltage.
        /// </summary>
        public static string GD_CATHODE_VOLTAGE_TITLE {
            get {
                return ResourceManager.GetString("GD_CATHODE_VOLTAGE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gun Driver Grid Drive Current.
        /// </summary>
        public static string GD_FILAMENT_CURRENT_TITLE {
            get {
                return ResourceManager.GetString("GD_FILAMENT_CURRENT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gun Driver Grid Drive Voltage.
        /// </summary>
        public static string GD_FILAMENT_VOLATAGE_TITLE {
            get {
                return ResourceManager.GetString("GD_FILAMENT_VOLATAGE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gun Driver Grid A Voltage.
        /// </summary>
        public static string GD_GRID_A_VOLTAGE_TITLE {
            get {
                return ResourceManager.GetString("GD_GRID_A_VOLTAGE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gun Driver Grid B Voltage.
        /// </summary>
        public static string GD_GRID_B_VOLTAGE_TITLE {
            get {
                return ResourceManager.GetString("GD_GRID_B_VOLTAGE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gun Driver Grid Bias.
        /// </summary>
        public static string GD_GRID_BIAS_TITLE {
            get {
                return ResourceManager.GetString("GD_GRID_BIAS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gun Driver Grid Drive Voltage.
        /// </summary>
        public static string GD_GRID_DRIVE_VOLTAGE_TITLE {
            get {
                return ResourceManager.GetString("GD_GRID_DRIVE_VOLTAGE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gun Driver Heater Current.
        /// </summary>
        public static string GD_HEATER_CURRENT_TITLE {
            get {
                return ResourceManager.GetString("GD_HEATER_CURRENT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gun Driver Heater Voltage.
        /// </summary>
        public static string GD_HEATER_VOLTAGE_TITLE {
            get {
                return ResourceManager.GetString("GD_HEATER_VOLTAGE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gun Driver State.
        /// </summary>
        public static string GD_STATE_TITLE {
            get {
                return ResourceManager.GetString("GD_STATE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gun driver has encountered an interlock..
        /// </summary>
        public static string GUN_DRIVER_INTERLOCK_STATUS_1 {
            get {
                return ResourceManager.GetString("GUN_DRIVER_INTERLOCK_STATUS_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display all information about the Linac system.
        /// </summary>
        public static string INFO_BUTTON_DESCRIPTION {
            get {
                return ResourceManager.GetString("INFO_BUTTON_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linac System.
        /// </summary>
        public static string INFO_BUTTON_TITLE {
            get {
                return ResourceManager.GetString("INFO_BUTTON_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ion Pump 1 Current.
        /// </summary>
        public static string ION_PUMP_1_CURRENT_TITLE {
            get {
                return ResourceManager.GetString("ION_PUMP_1_CURRENT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ion Pump 1 Voltage.
        /// </summary>
        public static string ION_PUMP_1_VOLTAGE_TITLE {
            get {
                return ResourceManager.GetString("ION_PUMP_1_VOLTAGE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ion Pump 2 Current.
        /// </summary>
        public static string ION_PUMP_2_CURRENT_TITLE {
            get {
                return ResourceManager.GetString("ION_PUMP_2_CURRENT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ion Pump 2 Voltage.
        /// </summary>
        public static string ION_PUMP_2_VOLTAGE_TITLE {
            get {
                return ResourceManager.GetString("ION_PUMP_2_VOLTAGE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ion Pump 3 Current.
        /// </summary>
        public static string ION_PUMP_3_CURRENT_TITLE {
            get {
                return ResourceManager.GetString("ION_PUMP_3_CURRENT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ion Pump 3 Voltage.
        /// </summary>
        public static string ION_PUMP_3_VOLTAGE_TITLE {
            get {
                return ResourceManager.GetString("ION_PUMP_3_VOLTAGE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kV.
        /// </summary>
        public static string KILOVOLTAGE_MEASUREMENT {
            get {
                return ResourceManager.GetString("KILOVOLTAGE_MEASUREMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material Discrimination.
        /// </summary>
        public static string LINAC_ENERGY_TYPE_STATE_0 {
            get {
                return ResourceManager.GetString("LINAC_ENERGY_TYPE_STATE_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Penetration.
        /// </summary>
        public static string LINAC_ENERGY_TYPE_STATE_1 {
            get {
                return ResourceManager.GetString("LINAC_ENERGY_TYPE_STATE_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Contrast.
        /// </summary>
        public static string LINAC_ENERGY_TYPE_STATE_2 {
            get {
                return ResourceManager.GetString("LINAC_ENERGY_TYPE_STATE_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low Dose.
        /// </summary>
        public static string LINAC_ENERGY_TYPE_STATE_3 {
            get {
                return ResourceManager.GetString("LINAC_ENERGY_TYPE_STATE_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Mode.
        /// </summary>
        public static string LINAC_ENGERY_TYPE_STATE_TITLE {
            get {
                return ResourceManager.GetString("LINAC_ENGERY_TYPE_STATE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linac Mode Selection.
        /// </summary>
        public static string LINAC_ENGERY_TYPE_TITLE {
            get {
                return ResourceManager.GetString("LINAC_ENGERY_TYPE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Ethernet connection to LINAC.
        /// </summary>
        public static string LINAC_ETHERNET_DISCONNECTED_1 {
            get {
                return ResourceManager.GetString("LINAC_ETHERNET_DISCONNECTED_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal System States.
        /// </summary>
        public static string LINAC_INTERNAL_SYSTEM_STATES_TITLE {
            get {
                return ResourceManager.GetString("LINAC_INTERNAL_SYSTEM_STATES_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Linac Faults.
        /// </summary>
        public static string LINAC_RESET_FAULT_BUTTON {
            get {
                return ResourceManager.GetString("LINAC_RESET_FAULT_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linac Faults.
        /// </summary>
        public static string LINAC_RESET_FAULT_TITLE {
            get {
                return ResourceManager.GetString("LINAC_RESET_FAULT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powered Off.
        /// </summary>
        public static string LINAC_STATE_0 {
            get {
                return ResourceManager.GetString("LINAC_STATE_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powered On.
        /// </summary>
        public static string LINAC_STATE_1 {
            get {
                return ResourceManager.GetString("LINAC_STATE_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warming Up.
        /// </summary>
        public static string LINAC_STATE_2 {
            get {
                return ResourceManager.GetString("LINAC_STATE_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Readying System.
        /// </summary>
        public static string LINAC_STATE_3 {
            get {
                return ResourceManager.GetString("LINAC_STATE_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X-Rays Off.
        /// </summary>
        public static string LINAC_STATE_4 {
            get {
                return ResourceManager.GetString("LINAC_STATE_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X-Rays On.
        /// </summary>
        public static string LINAC_STATE_5 {
            get {
                return ResourceManager.GetString("LINAC_STATE_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linac State.
        /// </summary>
        public static string LINAC_STATE_TITLE {
            get {
                return ResourceManager.GetString("LINAC_STATE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Healthy.
        /// </summary>
        public static string LINAC_STATUS_0 {
            get {
                return ResourceManager.GetString("LINAC_STATUS_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linac has encountered a Major fault.
        /// </summary>
        public static string LINAC_STATUS_1 {
            get {
                return ResourceManager.GetString("LINAC_STATUS_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linac has encounted a Minor fault and safety system must be reset..
        /// </summary>
        public static string LINAC_STATUS_2 {
            get {
                return ResourceManager.GetString("LINAC_STATUS_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Status.
        /// </summary>
        public static string LINAC_STATUS_TITLE {
            get {
                return ResourceManager.GetString("LINAC_STATUS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Healthy.
        /// </summary>
        public static string LINAC_STATUS_WIDGET_0 {
            get {
                return ResourceManager.GetString("LINAC_STATUS_WIDGET_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Major fault.
        /// </summary>
        public static string LINAC_STATUS_WIDGET_1 {
            get {
                return ResourceManager.GetString("LINAC_STATUS_WIDGET_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minor fault.
        /// </summary>
        public static string LINAC_STATUS_WIDGET_2 {
            get {
                return ResourceManager.GetString("LINAC_STATUS_WIDGET_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linac System Information.
        /// </summary>
        public static string LINAC_SYSTEM_INFO_TITLE {
            get {
                return ResourceManager.GetString("LINAC_SYSTEM_INFO_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magnetron and modulator encountered excessive current..
        /// </summary>
        public static string MAGNETRON_CURRENT_STATUS_1 {
            get {
                return ResourceManager.GetString("MAGNETRON_CURRENT_STATUS_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magnetron Current.
        /// </summary>
        public static string MAGNETRON_CURRENT_TITLE {
            get {
                return ResourceManager.GetString("MAGNETRON_CURRENT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linac has encountered excessive pressure in magnetron..
        /// </summary>
        public static string MAGNETRON_VACUUM_STATUS_1 {
            get {
                return ResourceManager.GetString("MAGNETRON_VACUUM_STATUS_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modulator Heater Current.
        /// </summary>
        public static string MD_HEATER_CURRENT_TITLE {
            get {
                return ResourceManager.GetString("MD_HEATER_CURRENT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modulator Heater Voltage.
        /// </summary>
        public static string MD_HEATER_VOLTAGE_TITLE {
            get {
                return ResourceManager.GetString("MD_HEATER_VOLTAGE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modulator HVPS Voltage.
        /// </summary>
        public static string MD_HVPS_VOLTAGE_TITLE {
            get {
                return ResourceManager.GetString("MD_HVPS_VOLTAGE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modulator State.
        /// </summary>
        public static string MD_STATE_TITLE {
            get {
                return ResourceManager.GetString("MD_STATE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uA.
        /// </summary>
        public static string MICROAMP_MEASUREMENT {
            get {
                return ResourceManager.GetString("MICROAMP_MEASUREMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modulator Filament Current.
        /// </summary>
        public static string MOD_FILAMENT_CURRENT_TITLE {
            get {
                return ResourceManager.GetString("MOD_FILAMENT_CURRENT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modulator Filament Voltage.
        /// </summary>
        public static string MOD_FILAMENT_VOLTAGE_TITLE {
            get {
                return ResourceManager.GetString("MOD_FILAMENT_VOLTAGE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modulator communications have been lost..
        /// </summary>
        public static string MODULATOR_COMMUNICATION_ERROR_STATUS_1 {
            get {
                return ResourceManager.GetString("MODULATOR_COMMUNICATION_ERROR_STATUS_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modulator has encountered an interlock..
        /// </summary>
        public static string MODULATOR_INTERLOCK_STATUS_1 {
            get {
                return ResourceManager.GetString("MODULATOR_INTERLOCK_STATUS_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RF Reflected Power.
        /// </summary>
        public static string REFLECTED_POWER_TITLE {
            get {
                return ResourceManager.GetString("REFLECTED_POWER_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magnetron encountered high reverse RF power..
        /// </summary>
        public static string REFLECTED_RF_POWER_STATUS_1 {
            get {
                return ResourceManager.GetString("REFLECTED_RF_POWER_STATUS_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linac SF6 gas is low.  Please refill SF6 gas to continue operations..
        /// </summary>
        public static string SF6_PRESSURE_STATUS_1 {
            get {
                return ResourceManager.GetString("SF6_PRESSURE_STATUS_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solenoid Magnet Current.
        /// </summary>
        public static string SOLENOID_CURRENT_MONITOR_TITLE {
            get {
                return ResourceManager.GetString("SOLENOID_CURRENT_MONITOR_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solenoid current is out of range..
        /// </summary>
        public static string SOLENOID_CURRENT_STATUS_1 {
            get {
                return ResourceManager.GetString("SOLENOID_CURRENT_STATUS_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solenoid Current.
        /// </summary>
        public static string SOLENOID_CURRENT_TITLE {
            get {
                return ResourceManager.GetString("SOLENOID_CURRENT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solenoid Magnet Voltage.
        /// </summary>
        public static string SOLENOID_VOLTAGE_MONITOR_TITLE {
            get {
                return ResourceManager.GetString("SOLENOID_VOLTAGE_MONITOR_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linac Status.
        /// </summary>
        public static string STATUSBAR_TITLE {
            get {
                return ResourceManager.GetString("STATUSBAR_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steering 1 Current.
        /// </summary>
        public static string STEERING_1_CURRENT_TITLE {
            get {
                return ResourceManager.GetString("STEERING_1_CURRENT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steering 2 Current.
        /// </summary>
        public static string STEERING_2_CURRENT_TITLE {
            get {
                return ResourceManager.GetString("STEERING_2_CURRENT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steering Magnet X Current Monitor.
        /// </summary>
        public static string STEERING_X_I_MON_TITLE {
            get {
                return ResourceManager.GetString("STEERING_X_I_MON_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steering Magnet Y Current Monitor.
        /// </summary>
        public static string STEERING_Y_I_MON_TITLE {
            get {
                return ResourceManager.GetString("STEERING_Y_I_MON_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stepper Process Variable.
        /// </summary>
        public static string STEPPER_PV_TITLE {
            get {
                return ResourceManager.GetString("STEPPER_PV_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TCU Temperature.
        /// </summary>
        public static string TCU_TEMPERATURE_TITLE {
            get {
                return ResourceManager.GetString("TCU_TEMPERATURE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to °F.
        /// </summary>
        public static string TEMPERATURE_MEASUREMENT {
            get {
                return ResourceManager.GetString("TEMPERATURE_MEASUREMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNKNOWN ERROR.
        /// </summary>
        public static string UNKNOWN_RESOURCE {
            get {
                return ResourceManager.GetString("UNKNOWN_RESOURCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V.
        /// </summary>
        public static string VOLTAGE_MEASUREMENT {
            get {
                return ResourceManager.GetString("VOLTAGE_MEASUREMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linac System Warnings.
        /// </summary>
        public static string WARNING_MESSAGES_TITLE {
            get {
                return ResourceManager.GetString("WARNING_MESSAGES_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W.
        /// </summary>
        public static string WATTAGE_MEASUREMENT {
            get {
                return ResourceManager.GetString("WATTAGE_MEASUREMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linac RF components experienced excessive arcing in power..
        /// </summary>
        public static string WAVEGUIDE_ARC_STATUS_1 {
            get {
                return ResourceManager.GetString("WAVEGUIDE_ARC_STATUS_1", resourceCulture);
            }
        }
    }
}
